### ISSUE TITLE
ISSUE: iCloud IMAP server not supported

### ISSUE THREAD

**Issue by rscheuermann** [moralmunky/Home-Assistant-Mail-And-Packages#1005]
**Describe the bug**
Using iCloud's IMAP server (imap.mail.me.com) will never find and process emails because IMAP's server does not support `RFC822` fetch protocol.

The solution is to switch to `BODY[]`. I've done this in my local helpers.py and it works!

See: https://stackoverflow.com/questions/75444763/python-imaplib-fetching-icloud-mail-rfc822-not-working

I'll open a PR to fix as soon as I'm able.

**Environment (please complete the following information):**
 - OS: Docker
 - Type of device: Synology
 - Home Assistant version: 2024.11.2
 - Hassio/Docker/Core? Docker
 - Component version: 0.4.1

**Logs**
When using iCloud, the FETCH result will always look like this:

```
2024-11-18 10:36:51.087 DEBUG (SyncWorker_9) [custom_components.mail_and_packages.helpers] email_search value: ('OK', [b'1'])
```

**Screenshots**
N/A

**Additional context**
The fix may require introducing a new configuration variable to switch from RFC822 to BODY[] fetch parameters. Switching the core code to BODY[] for all mail servers may break backwards compatibility.

**Comment by ID-Ant** [comment]
hi @rscheuermann - would you mind post more detail on how you resolved this please?

**Comment by firstof9** [comment]
Anywhere `email_fetch` is called the (RFC822) will need to be adjusted in the call.

Plan is to modify the function to check if you're using iCloud's monstrosity of an IMAP server, and adjust the call accordingly in a single spot.

**Comment by firstof9** [comment]
Please download the file: 

https://github.com/firstof9/Home-Assistant-Mail-And-Packages/blob/fix-1005/custom_components/mail_and_packages/helpers.py

and place it in your `custom_components/mail_and_packages/` directory and reload HA.

Please let me know if that solves your iCloud troubles.

**Comment by firstof9** [comment]
Actually I'll drop this in a beta release for testing.

**Comment by ID-Ant** [comment]
> Please download the file:
> 
> https://github.com/firstof9/Home-Assistant-Mail-And-Packages/blob/fix-1005/custom_components/mail_and_packages/helpers.py
> 
> and place it in your `custom_components/mail_and_packages/` directory and reload HA.
> 
> Please let me know if that solves your iCloud troubles.

Thanks, will be back later today (just away for work) and will let you know how it goes either this evening or tomorrow.

**Comment by jbistis** [comment]
Thanks, I am getting a 404 - page not found when trying to access the fix-1005 link in the previous post.  Did it get pushed someplace else?

**Comment by firstof9** [comment]
I dropped it into the latest beta available for upgrade via HACS

**Comment by jbistis** [comment]
Just tried the install with the latest beta and it installed without any issues!  Thanks!!

**Comment by firstof9** [comment]
No errors when it went looking for your mail?

**Comment by ID-Ant** [comment]
@firstof9 im getting the following error:

```
Invalid config
The following integrations and platforms could not be set up:

[mail_and_packages](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages)(http://homeassistant.local:8123/config/logs?filter=mail_and_packages))
Please check your config and [logs](http://homeassistant.local:8123/config/logs).
```
and the logs show:

```
Log details (ERROR)


Logger: homeassistant.setup
Source: setup.py:334
First occurred: 10:13:59 AM (1 occurrences)
Last logged: 10:13:59 AM

Setup failed for custom integration 'mail_and_packages': Unable to import component: Exception importing custom_components.mail_and_packages
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mail_and_packages/__init__.py", line 31, in <module>
    from .helpers import process_emails
  File "/config/custom_components/mail_and_packages/helpers.py", line 100
    <title>Home-Assistant-Mail-And-Packages/custom_components/mail_and_packages/helpers.py at dev · firstof9/Home-Assistant-Mail-And-Packages</title>
                                                                                                  ^
SyntaxError: invalid character '·' (U+00B7)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.mail_and_packages

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mail_and_packages/__init__.py", line 31, in <module>
    from .helpers import process_emails
  File "/config/custom_components/mail_and_packages/helpers.py", line 100
    <title>Home-Assistant-Mail-And-Packages/custom_components/mail_and_packages/helpers.py at dev · firstof9/Home-Assistant-Mail-And-Packages</title>
                                                                                                  ^
SyntaxError: invalid character '·' (U+00B7)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1085, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.mail_and_packages
```

and

```
Log details (ERROR)


Logger: homeassistant.loader
Source: loader.py:1074
First occurred: 10:13:59 AM (2 occurrences)
Last logged: 10:13:59 AM

Unexpected exception importing component custom_components.mail_and_packages
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mail_and_packages/__init__.py", line 31, in <module>
    from .helpers import process_emails
  File "/config/custom_components/mail_and_packages/helpers.py", line 100
    <title>Home-Assistant-Mail-And-Packages/custom_components/mail_and_packages/helpers.py at dev · firstof9/Home-Assistant-Mail-And-Packages</title>
                                                                                                  ^
SyntaxError: invalid character '·' (U+00B7)
````

**Comment by jbistis** [comment]
Correct, no errors found when it went looking through email and I received my first mail notifications, USPS.

**Comment by firstof9** [comment]
> @firstof9 im getting the following error:

@ID-Ant 
Looks like your download is corrupted. You can grab the zip file from the releases and manually extract over the directory.

**Comment by ID-Ant** [comment]
> Looks like your download is corrupted.

@firstof9  - So it was :), why i didn't spot that - okay updated without errors, guess i'll have to order something from amazon now to test it :)

**Comment by ID-Ant** [comment]
Hi @firstof9 - so I've got an Order Confirmation email sitting in my inbox, should I be expecting that to be picked up by the sensor.mail_amazon_packages ? if so, this is not being picked up.

**Comment by firstof9** [comment]
> should I be expecting that to be picked up by the sensor.mail_amazon_packages ?

Only on the day of it's expected arrival.

**Comment by ID-Ant** [comment]
hi @firstof9 - so got the:

> Out for delivery
> --
> 
> Your package will arrive
> Today

email, however the sensor.mail_amazon_packages is showing as below (has the order number, but saying 0 Package(s))

<img width="635" alt="Screenshot 2024-12-18 at 11 10 20" src="https://github.com/user-attachments/assets/4a541f88-b687-4f61-9068-c54773754ba6" />

**Comment by firstof9** [comment]
There's no parsing for an amazon email stating "out for delivery".

**Comment by ID-Ant** [comment]
Ah right, sorry, just my lack of understanding then - thanks for the help - could this be a future update :)

**Comment by firstof9** [comment]
> could this be a future update

Not really, I've never seen an "out for delivery" email from amazon ever.
Amazon parsing checks the date from the order confirmation email and uses that date to tick up the counter.

**Comment by ID-Ant** [comment]
oh right, maybe it's a UK only thing coming form amazon.co.uk, can pass on if you want? - but got the package delivered and sensor.mail_amazon_packages_delivered updated as expected to show 1 package(s); still a bit confused as to what sensor.mail_amazon_packages does though.

**Comment by firstof9** [comment]
> till a bit confused as to what sensor.mail_amazon_packages does though.

I've [covered it in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon)

**Comment by rscheuermann** [comment]
@firstof9 Sorry for the delay! LGTM!
