### ISSUE TITLE
[Feature Request] Adding Post Austria

### ISSUE THREAD

**Issue by TheMRX13** [moralmunky/Home-Assistant-Mail-And-Packages#1007]
if Possible Please add "Post Austria". In austria we get the most packages with Post Austria
if u guys need any Details or TrackerID's for Testing. I have a couple ones.

LINK:
https://www.post.at/en/

**Comment by firstof9** [comment]
Need email from addresses, subject lines, and example tracking numbers.

**Comment by TheMRX13** [comment]
**Addresses:**
MeineSendung@post.at

**Subject lines**
So stellen wir Ihre Sendung (1040555009000180164609) zu
Ihre Pascal Keller-Sendung ist in Verteilung

The code in the first line is the tracking code. 
The name "Pascal Keller" is the package name or who send it. The part "-Sendung ist in Verteilung" is always there.

**Example Tracking Numbers (all a real tracking codes)**
1040555009000180164609
1040555009000140164601
1040555009000160164605
1040555009000120164607
1043733011500910264608

to provide an real e-mail i would need a email address where i can send it. The eml files are encrypted.

**Comment by firstof9** [comment]
they send encrypted emails?

**Comment by TheMRX13** [comment]
Na. The eml files encrypted. The emails it self are normal

**Comment by firstof9** [comment]
Ok, which subject lines are for:

Out for delivery:
Delivered:

Thanks.

**Comment by TheMRX13** [comment]
Ihre Pascal Keller-Sendung ist in Zustellung

out for delivery

and
Deliverd:
Ihre Sendung wurde Zugestellt

**Comment by TheMRX13** [comment]
it reads what text is in the emails and that changed the entity?

**Comment by firstof9** [comment]
We parse the tracking numbers to give you a proper package count.
If we don't have to go parse the email that makes things slightly faster.

**Comment by TheMRX13** [comment]
Post Austria has an API. how long will it take for an update?

**Comment by firstof9** [comment]
We don't use APIs as they usually cost money to use

**Comment by TheMRX13** [comment]
okay. but how long for update?

**Comment by firstof9** [comment]
I'll drop a new beta in a few moments you can test with :slightly_smiling_face:

**Comment by firstof9** [comment]
[0.4.2-b4](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b4)

Let me know how it works out for you.

**Comment by TheMRX13** [comment]
beta is installed

while reconfigure the integrations this errors came up [Gmail]
```
2024-11-20 16:13:25.103 ERROR (SyncWorker_39) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:13:25.104 ERROR (SyncWorker_39) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:13:25.105 ERROR (SyncWorker_39) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:13:25.106 ERROR (SyncWorker_39) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:13:25.107 ERROR (SyncWorker_39) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```
and the Packages dont show up. 4 are in my email account

here the subjects again:

**Address:**
from: MeineSendung@post.at
send from: em6648.post.at
(idk what that means)
![chrome_HeRSsrH9EO](https://github.com/user-attachments/assets/19caa9de-e474-40f1-81ad-211d06eea521)


**In Transit**
Ihre Pascal Keller-Sendung ist in Verteilung
*The "Pascal Keller" part is the Package name*
So stellen wir Ihre Sendung (1040555009000140164601) zu
*The () part is the tracking code*

**Out for Delivery**
Ihre Pascal Keller-Sendung ist in Zustellung
*The "Pascal Keller" part is the Package name*

**Deliverd**
Ihre Sendung wurde zugestellt

**Comment by firstof9** [comment]
Seems like something happened while reloading, any additional errors in the logs?

**Comment by TheMRX13** [comment]
only what i got is this here
Tryed to reboot HA but still same issues

```
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "", line 198, in _run_module_as_main
  File "", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in 
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/mail_and_packages/config_flow.py", line 487, in async_step_reconfigure
    valid = await _test_login(
  File "/config/custom_components/mail_and_packages/helpers.py", line 122, in _test_login
    context = ssl.create_default_context()
2024-11-20 16:35:05.967 ERROR (SyncWorker_0) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:35:05.968 ERROR (SyncWorker_0) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:35:05.969 ERROR (SyncWorker_0) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
2024-11-20 16:35:05.970 ERROR (SyncWorker_0) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```

**Comment by firstof9** [comment]
try unchecking Verify SSL cert

**Comment by TheMRX13** [comment]
still
```
2024-11-20 17:14:38.067 ERROR (SyncWorker_35) [custom_components.mail_and_packages.helpers] Error searching emails: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```

**Comment by firstof9** [comment]
Are your sensors unavailable?

**Comment by TheMRX13** [comment]
![chrome_j1joiUszpm](https://github.com/user-attachments/assets/19870fe4-4384-40cc-a2cd-136ad4caaae6)

**Comment by firstof9** [comment]
You may need to do the debug logging so I can see where/why that error's coming up.

**Comment by TheMRX13** [comment]
Sure. Here a 2 Logs. with and without verify ssl 
[Debug log without verify ssl.log](https://github.com/user-attachments/files/17836372/Debug.log.without.verify.ssl.log)
[Debug log with verify ssl.log](https://github.com/user-attachments/files/17836375/Debug.log.with.verify.ssl.log)

**Comment by firstof9** [comment]
I am not sure what is happening with your instance, it doesn't seem to be attempting to login to the IMAP server.

**Comment by firstof9** [comment]
Only thing I can think to suggest is, remove the mail and packages configuration.
Delete the files from custom_integrations and re-download/reinstall/reconfigure.

**Comment by TheMRX13** [comment]
Im connected Via google. I choose one of all my folders. I tryed the 2 main folders. INBOX and GMAIL. I cant tell ya whats the issue here.

**Comment by firstof9** [comment]
Ya just 'INBOX' should be the one.

**Comment by TheMRX13** [comment]
I habe it on INBOX. But wont work

**Comment by firstof9** [comment]
Attempt the reinstall method.

**Comment by TheMRX13** [comment]
the "command SEARCH illegal in state AUTH" error is gone but still 0 packages and other another error with the integration

[home-assistant_mail_and_packages_2024-11-21T10-44-49.188Z.log](https://github.com/user-attachments/files/17844356/home-assistant_mail_and_packages_2024-11-21T10-44-49.188Z.log)

**Comment by firstof9** [comment]
The IO blocking message you can ignore for now.

```
2024-11-21 11:44:29.425 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['MeineSendung@post.at']) with subject (Ihre Sendung wurde Zugestellt)
2024-11-21 11:44:29.425 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] DEBUG subject: Ihre Sendung wurde Zugestellt
2024-11-21 11:44:29.425 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "MeineSendung@post.at" SUBJECT "Ihre Sendung wurde Zugestellt" SINCE 21-Nov-2024)
2024-11-21 11:44:29.674 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] email_search value: ('OK', [b''])
2024-11-21 11:44:29.675 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Search for (['MeineSendung@post.at']) with subject (Ihre Sendung wurde Zugestellt) results: b'' count: 0
2024-11-21 11:44:29.675 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Sensor: post_at_delivered Count: 0
2024-11-21 11:44:29.675 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['MeineSendung@post.at']) with subject (Sendung ist in Zustellung)
2024-11-21 11:44:29.675 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] DEBUG subject: Sendung ist in Zustellung
2024-11-21 11:44:29.675 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "MeineSendung@post.at" SUBJECT "Sendung ist in Zustellung" SINCE 21-Nov-2024)
2024-11-21 11:44:29.906 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] email_search value: ('OK', [b''])
2024-11-21 11:44:29.906 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Search for (['MeineSendung@post.at']) with subject (Sendung ist in Zustellung) results: b'' count: 0
2024-11-21 11:44:29.906 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Sensor: post_at_delivering Count: 0
2024-11-21 11:44:29.906 DEBUG (SyncWorker_11) [custom_components.mail_and_packages.helpers] Sensor: post_at_packages Count: 0
```

This shows no search results in your email currently, that's why the counts remain `0`

**Comment by TheMRX13** [comment]
can i chang some lines on my local HA? i try to fix the problem

**Comment by TheMRX13** [comment]
for what is "post_at_exception" ?

**Comment by TheMRX13** [comment]
I figured out what happened—the states weren’t correct. I fixed them, and now it’s working. I’ll collect some lines and add them to the code. Once I’ve collected them, I’ll post all of them. Also, is it possible to add a sensor for "shipment in distribution"? We get emails when there’s a new package on the way. If possible, just add it, and I’ll collect the necessary lines for it and send them to you later so you can include them.

**Comment by firstof9** [comment]
The integration is only for "out for delivery" and "delivered" packages/mail.

**Comment by firstof9** [comment]
> for what is "post_at_exception" ?

For some carriers like UPS or FedEX, they send 'exception' emails for when a package has been delayed, that's what that's for if the carrier sends them.

**Comment by TheMRX13** [comment]
Hm. Okay. I need "In distribution" as well. Too bad. I guess I’ll have to write my own integration for that. I need it for automations... But thank you! Your integration is great otherwise, and I’ll keep using it! I’ll still collect the code lines!
