### ISSUE TITLE
ISSUE: Unable to login to Outlook.com

### ISSUE THREAD

**Issue by shooolme** [moralmunky/Home-Assistant-Mail-And-Packages#1014]
Attempting to login to Outlook using an app password fails.

 - OS: HassOS
 - Type of device: NUC
 - Home Assistant version: 2024.11.2
 - Core
 - Component version: 0.4.1

```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 2:41:37 PM (1 occurrences)
Last logged: 2:41:37 PM

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fa66d2952d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 122: context = ssl.create_default_context() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start task = asyncio.Task(coro, loop=loop, eager_start=True) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/mail_and_packages/config_flow.py", line 322, in async_step_user valid = await _test_login( File "/config/custom_components/mail_and_packages/helpers.py", line 122, in _test_login context = ssl.create_default_context()
```

![image](https://github.com/user-attachments/assets/96bfecbf-f60a-48f1-b81f-91256ec1d0b8)

**Comment by firstof9** [comment]
The logged message you included means nothing, check your `home-assistant.log` file for the real error message.

**Comment by shooolme** [comment]
[home-assistant.log](https://github.com/user-attachments/files/17873797/home-assistant.log)

Got the correct log!

**Comment by firstof9** [comment]
```
2024-11-22 11:14:52.072 ERROR (MainThread) [custom_components.mail_and_packages.helpers] Error logging into IMAP Server: b'LOGIN failed.'
```

Your login failed.

**Comment by dirtdagg** [comment]
Same issue for me.

I setup Two-Factor Authentication on my outlook account, created an App Password, and tried to reconfigure my original integration with the latest settings, failed after multiple attempts.

Tried setting up the integration from scratch and still saw the same error, "Unable to connect or login to the mail server. Please check the log for details." I'm positive I've used the correct App Password (tried multiple times, regenerated and each one hasn't worked). Tried setting up the integration with IMAP, POP, and SMTP settings, none worked.

**Comment by shooolme** [comment]
I've ensured IMAP is enabled on my account but I am not seeing any login attempts.

**Comment by stub2k2** [comment]
I third this issue. I have double checked the password, created an app password, made sure imap and pop are all enabled. Can't login.

**Comment by firstof9** [comment]
The issue is outlook.com/live.com rejecting your login.
That's an issue server side.

**Comment by dirtdagg** [comment]
To clarify, does that mean you've tested outlook/live login and have them working, this problem is isolated to some accounts? Or does outlook/live reject all logins from this service for whatever reason?

**Comment by firstof9** [comment]
It look like outlook/live is rejecting the login for some reason.

**Comment by eymericguyot** [comment]
Getting same problem. Created app password:
Error logging into IMAP Server: b'[ALERT] Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure)'
Error logging into IMAP Server: b'LOGIN failed.'
Error logging into IMAP Server: command: LOGIN => socket error: EOF

**Comment by nathanfiscus** [comment]
It's rejected because Microsoft has disabled Basic Auth via IMAP. See here: [https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d](https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d)

If someone could add OAuth 2.0 for IMAP then you could connect your Outlook address again.

Edit

Google is doing the same: [https://support.google.com/a/answer/14114704?hl=en](https://support.google.com/a/answer/14114704?hl=en)

**Comment by jbistis** [comment]
Encountering the same issue. I created an app password and still cannot connect.

**Comment by henkha** [comment]
Same Issue here. IMAP is properly enabled and App-Password has been created. Both are tested to work from a mail client. Only the HA Integration refuses to connect.

**Comment by firstof9** [comment]
> Same Issue here. IMAP is properly enabled and App-Password has been created. Both are tested to work from a mail client. Only the HA Integration refuses to connect.

As @nathanfiscus linked they're disabling basic auth. The mail clients utilize oauth.

**Comment by stub2k2** [comment]
Still an issue.  Bump

**Comment by sabasp96** [comment]
I've been having this same issue. Is there any plan on adding OAuth 2.0 authentication to the integration?

Or is it time to switch email services?

**Comment by stub2k2** [comment]
> Or is it time to switch email services?

seems like a bad reason to switch email providers. unless you are on the fence already. I would bet others will move to the new security sooner than later anyway. One workaround that would require less of an upheaval. You could create rules in outlook.com to forward all delivery email to a gmail/yahoo/etc, then register that email with this plugin. Also added benefit of only giving the software access to those emails for scraping.

**Comment by henkha** [comment]
The issue still exists. Modern Authentication is the way to go!

**Comment by eon0613** [comment]
just to confirm...issue still exist..please fix :)

**Comment by rafaelmathieu** [comment]
@firstof9 Would that be something that would get fixed with the implementation of https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/858 ?

**Comment by firstof9** [comment]
Yup, it's not as easy to implement as one would think.

**Comment by devinalonzo** [comment]
bump I am having this issue as well

**Comment by pr8x** [comment]
Experiencing the same issue :/

**Comment by stub2k2** [comment]
bump. still broken

**Comment by BMWfan** [comment]
Perhaps this project helps to integrate it?

https://github.com/RogerSelwyn/MS365-Mail

**Comment by dwlyles** [comment]
I also have this problem

**Comment by jhalak1984** [comment]
I have the same, any fix yet?

**Comment by martinwierenga** [comment]
I there any update of it would be fixed or is on roadmap to fix?
I would love to use my Outlook.com email but a change to XOAUTH2 needs to be done. An example like this but we would need app registration done when user is doing setup (only Mail.ReadWrite is necessary) https://stackoverflow.com/questions/73368376/use-imap-with-xoauth2-and-ms365-application-permissions-to-authenticate-imap-for

**Comment by firstof9** [comment]
Since Home Assistant's built in oauth system can't handle multiple oauth (one for gmail, one for o365, etc) a new one would need to be created.

**Comment by Shredder5262** [comment]
Broken for me also.

**Comment by firstof9** [comment]
I've found this container:
https://github.com/blacktirion/email-oauth2-proxy-docker

Which uses https://github.com/simonrob/email-oauth2-proxy/tree/main

to provide an oauth email proxy.

**Comment by BMWfan** [comment]
> I've found this container: https://github.com/blacktirion/email-oauth2-proxy-docker
> 
> Which uses https://github.com/simonrob/email-oauth2-proxy/tree/main
> 
> to provide an oauth email proxy.

And you will add it to your homeassistant plugin?

**Comment by firstof9** [comment]
> And you will add it to your homeassistant plugin?

This is an integration not a "plugin", and no integrations can't add containers.

**Comment by skupu** [comment]
cannot login to hotmail

**Comment by ExtremeHobo** [comment]
Same here, hotmail/outlook is not working.

**Comment by firstof9** [comment]
@ExtremeHobo What are your logs saying?

**Comment by karpach** [comment]
I am unable to loging to outlook.com.

Logs:
Error fetching Mail and Packages (outlook.office365.com) data: b'[Error="AuthFailed:LogonDenied-BasicAuthBlocked-<RequestId=a72c4922-23ab-4d80-b5ea-df75b0cdd734,ST=02:03:58><Process:Microsoft.Exchange.Security.BasicAuthService.Server><BG<UserType:OutlookCom><LogonFailed-BasicAuthBlocked><AS:BasicAuthBlocked>

**Comment by firstof9** [comment]
@karpach Username and password authentication is blocked by Microsoft. See https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/1014#issuecomment-3214402181 for a work around.

**Comment by karpach** [comment]
> [@karpach](https://github.com/karpach) Username and password authentication is blocked by Microsoft. See [#1014 (comment)](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/1014#issuecomment-3214402181) for a work around.

Thank you, it was not simple, but I finally made it work using email proxy docker.

**Comment by firstof9** [comment]
Ya it took me a moment to figure out the configuration syntax, but after that it works great.

**Comment by townsmcp** [comment]
Just seen this, what settings do you use in Mail and Packages? Do you still use your hotmail email address and password? and IP and port of the docker container? 
Any settings changes from default? I have the docker container running and logs appear to be fine form that:
```
2026-01-31 10:52:31,054: Initialising Email OAuth 2.0 Proxy (version 2025-10-14) in debug mode from config file /config/emailproxy.config

2026-01-31 10:52:31,055: Starting IMAP server at 127.0.0.1:1993 (unsecured) proxying outlook.office365.com:993 (SSL/TLS)

2026-01-31 10:52:31,056: Starting POP server at 127.0.0.1:1995 (unsecured) proxying outlook.office365.com:995 (SSL/TLS)

2026-01-31 10:52:31,057: Starting SMTP server at 127.0.0.1:1587 (unsecured) proxying smtp-mail.outlook.com:587 (STARTTLS)

2026-01-31 10:52:31,057: Initialised Email OAuth 2.0 Proxy - listening for authentication requests. Connect your email client to begin
```

**Comment by firstof9** [comment]
> Do you still use your hotmail email address and password?

Use your email address as the username, and whatever you want as the password.


> what settings do you use in Mail and Packages?

IMAP server will be whatever your container IP is with which ever port you're using, based on your log looks like 1993

**Comment by townsmcp** [comment]
Thanks @firstof9 - got the proxy working. Needed a bit of tweaking with the help of ChatGPT as I went with the new MS application/Entra.
Lol only issue is now, after selecting the Inbox form Outlook mailbox and selecting the mail services I want to watch for I keep getting a `Failed setup, will retry: None` on the integration

**Comment by firstof9** [comment]
Check the HA logs as to why it's failing.

**Comment by vivis996** [comment]
Same issue on Version 0.4.7
```
500 Internal Server Error

Server got itself in trouble
```

<img width="322" height="608" alt="Image" src="https://github.com/user-attachments/assets/ff41c289-c871-4b4e-a59f-1871bd49834b" />

**Comment by firstof9** [comment]
Please see https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/1014#issuecomment-3214402181 for a workaround due to OAuth.
