### ISSUE TITLE
ISSUE: setting up icloud is able to completely crash home-assistant

### ISSUE THREAD

**Issue by snickers2k** [moralmunky/Home-Assistant-Mail-And-Packages#1040]
**Describe the bug**
i'm trying to set up icloud, but everytime, home-assistant completely crashes (needs physical reboot)

**Environment (please complete the following information):**
 - OS: latest HASS-OS
 - Type of device: NUC
 - Home Assistant version: 2024.12.x
 - Hassio/Docker/Core? 
 - Component version: 2024.12.x

**Logs**
[config_entry-mail_and_packages-01JFFM6EDKA7VV97J7PG1F8KR1.json](https://github.com/user-attachments/files/18207195/config_entry-mail_and_packages-01JFFM6EDKA7VV97J7PG1F8KR1.json)

**Comment by firstof9** [comment]
What integration version?
What shows up in your `home-assistant.log` file?

**Comment by the-smart-home-maker** [comment]
Hi,  

I have the same problem when just trying to set up mail and packages with Gmail. In step 1, when typing in my email provider settings and clicking next to get to step 2, Home Assistant completely crashes and restarts.

I am using version 0.4.2 of Mail and Packages.

Type of device: Raspberry Pi 4
Home Assistant Core: 2024.12.5
Home Assistant Supervisor; 2024.12.0
HASS Operating System: 14.1
Frontend: 20241127.8

Here is the log from Home Assistant Supervisor:

```
2024-12-22 08:04:20.318 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:04:44.318 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:04:44.318 WARNING (MainThread) [supervisor.misc.tasks] Watchdog missed an Home Assistant Core API response.
2024-12-22 08:04:44.319 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:05:45.330 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:06:01.329 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:07:15.319 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:07:15.323 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:07:15.324 ERROR (MainThread) [supervisor.misc.tasks] Watchdog missed 2 Home Assistant Core API responses in a row. Restarting Home Assistant Core!
2024-12-22 08:07:15.337 INFO (SyncWorker_1) [supervisor.docker.manager] Restarting homeassistant
2024-12-22 08:08:15.316 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:08:42.319 ERROR (MainThread) [supervisor.homeassistant.api] Timeout on call http://172.30.32.1:8123/api/core/state.
2024-12-22 08:08:58.251 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-46884' coro=<HomeAssistantWebSocket.async_supervisor_event() done, defined at /usr/src/supervisor/supervisor/homeassistant/websocket.py:322> exception=AttributeError("'NoneType' object has no attribute 'close'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 267, in async_send_message
    await self._client.async_send_command(message)
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 95, in async_send_command
    return await self._futures[message["id"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
supervisor.exceptions.HomeAssistantWSConnectionError: Connection was closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 327, in async_supervisor_event
    await self.async_send_message(
  File "/usr/src/supervisor/supervisor/homeassistant/websocket.py", line 269, in async_send_message
    await self._client.close()
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
2024-12-22 08:08:58.397 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/core/state: Cannot connect to host 172.30.32.1:8123 ssl:False [Connect call failed ('172.30.32.1', 8123)]
```

I had two restarts in a row when trying to get this set up.

**Comment by firstof9** [comment]
> Type of device: Raspberry Pi 4

How much RAM is on this Pi4?

**Comment by firstof9** [comment]
> * Type of device: NUC

@snickers2k you running proxmox or HAOS baremetal on the NUC? Also, how much RAM?

**Comment by the-smart-home-maker** [comment]
> > Type of device: Raspberry Pi 4
> 
> How much RAM is on this Pi4?

4 GB

**Comment by firstof9** [comment]
@the-smart-home-maker and anything in the `home-assistant.log` file? supervisor logs don't tell me anything.

**Comment by the-smart-home-maker** [comment]
Unfortunately not - no log entry at all around this time stamp in the Home Assistant Core Logs. Sorry!

**Comment by firstof9** [comment]
Sorry it'd be technically `home-assistant.log.1` HA makes that when it crashes.

**Comment by snickers2k** [comment]
> > * Type of device: NUC
> 
> @snickers2k you running proxmox or HAOS baremetal on the NUC? Also, how much RAM?

sorry, being not home for a few days. i'll test asap. 
i'm running baremetal with NUC and 8gb ram (at 60-70% usage)

**Comment by snickers2k** [comment]
> Unfortunately not - no log entry at all around this time stamp in the Home Assistant Core Logs. Sorry!

did you activated "debug protocol" inside the integration already? maybe thats logging something helpful

**Comment by firstof9** [comment]
I'm suspecting both of your HA's are OOMing (out of memory).

**Comment by snickers2k** [comment]
no.. again, my ram is always around 60% .. i never experienced crashing HA before this integration (in years). and it did crash around 5 times trying setting up icloud. it's always crashing. it's repeatable. gmail works fine though

**Comment by firstof9** [comment]
> gmail works fine though

Very odd, I would expect it to fail completely no matter the IMAP server. The guys over in #1005 aren't reporting these types of problems.

**Comment by the-smart-home-maker** [comment]
Hi there,

I got it. I had a typo in the Mail Server address. Now that the typo is gone, it does not crash any more. But I guess it should never crash but just give an error message.

Best,
The Smart Home Maker

**Comment by firstof9** [comment]
> I got it. I had a typo in the Mail Server address. Now that the typo is gone, it does not crash any more. But I guess it should never crash but just give an error message.

Normally that's how it works, this is the first time I've heard of this type of issue.
