### ISSUE TITLE
ISSUE: email FROM amazon.com includes more than order messages

### ISSUE THREAD

**Issue by stogs** [moralmunky/Home-Assistant-Mail-And-Packages#106]
Amazon sensor fails to update if it finds non-order emails.  Currently the process only looks for emails from amazon.com, which can include different types of emails other than orders such as ads or alexa tips.  Looking for auto-confirm@amazon.com seems to narrow it down to just orders.

<img width="647" alt="Screen Shot 2020-04-26 at 12 07 49 PM" src="https://user-images.githubusercontent.com/42517518/80316663-ac2a1400-87c4-11ea-990d-f3e2f3160b96.png">

```
2020-04-26 10:48:44 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /home/homeassistant/.homeassistant/images/mail_and_packages/
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 0
2020-04-26 10:48:45 INFO (MainThread) [custom_components.mail_and_packages.sensor] No mail found.
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Copying nomail gif
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject Item Delivered
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject Expected Delivery on
2020-04-26 10:48:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject Your UPS Package was delivered
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject UPS Update: Package Scheduled for Delivery Today
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from mcinfo@ups.com with subject UPS Update: Follow Your Delivery on a Live Map
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject Your package has been delivered
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject Delivery scheduled for today
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from TrackingUpdates@fedex.com with subject Your package is scheduled for delivery today
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-04-26 10:48:46 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 5
2020-04-26 10:48:47 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 69, in async_setup_entry
    async_add_entities([MailCheck(data), USPS_Mail(hass, data),
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 185, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 225, in update
    self.data.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 161, in update
    self._amazon_packages = get_items(account, "count")
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 1248, in get_items
    email_msg = str(msg.get_payload(0))
  File "/usr/lib/python3.7/email/message.py", line 257, in get_payload
    raise TypeError('Expected list, got %s' % type(self._payload))
TypeError: Expected list, got <class 'str'>
```

**Comment by firstof9** [comment]
As a work around you could try deleting the other amazon emails for now until we can get a fix in place.

**Comment by firstof9** [comment]
Give the latest beta a whirl should fix those errors right up now.

**Comment by stogs** [comment]
Looks good, thanks for the quick turnaround!
