### ISSUE TITLE
ISSUE: Error while setting up mail_and_packages platform for sensor

### ISSUE THREAD

**Issue by brendanm720** [moralmunky/Home-Assistant-Mail-And-Packages#129]
**Describe the bug**
Sensor for this integration in Home Assistant (HassIO) does not start properly.

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]  HassOS
 - Type of device: [e.g. RPi3/NUC/Synology]  HyperV Virtual Machine on Hyper-V Core 2012 R2
 - Home Assistant version: [e.g. 0.105.5] 0.109.6
 - Hassio/Docker/Core? Hassio
 - Component version: [e.g. 0.1.2] 0.1.5

**Logs**
Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:1054
Integration: Sensor (documentation, issues)
First occurred: 3:32:27 PM (1 occurrences)
Last logged: 3:32:27 PM

Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 69, in async_setup_entry
    async_add_entities([MailCheck(data), USPS_Mail(hass, data),
  File "/config/custom_components/mail_and_packages/sensor.py", line 185, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 225, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 131, in update
    self._gif_duration, self._image_name)
  File "/config/custom_components/mail_and_packages/sensor.py", line 1054, in get_mails
    USPS_Mail_Subject + '" SENTON "' + today + '")'
  File "/usr/local/lib/python3.7/imaplib.py", line 723, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/local/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.7/imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/local/lib/python3.7/imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "/usr/local/lib/python3.7/imaplib.py", line 1047, in _get_response
    resp = self._get_line()
  File "/usr/local/lib/python3.7/imaplib.py", line 1149, in _get_line
    line = self.readline()
  File "/usr/local/lib/python3.7/imaplib.py", line 310, in readline
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
Connection lost. Reconnecting…

**Screenshots**

**Additional context**
My IMAP server is not GMAIL, and uses the "SSL/TLS" method of encryption, and not "STARTTLS".  I'm not sure if this is relevant or not.

The sensor.mail_deliveries_message entity states that "No mail will be delivered. No packages are in transit."  There are 7 or 8 messages in the inbox of the account.
![MaP1](https://user-images.githubusercontent.com/57099145/82253193-76d59980-991e-11ea-812c-b5c236693205.PNG)
![MaP2](https://user-images.githubusercontent.com/57099145/82253205-7c32e400-991e-11ea-86a9-04d3dbd75af7.PNG)

**Comment by brendannm720** [comment]
I am also seeing a bunch of the following lines in the log:

2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.
2020-05-18 15:45:02 WARNING (MainThread) [asyncio] socket.send() raised exception.

Thanks!

**Comment by firstof9** [comment]
You are attempting to use a POP connection, this integration only supports IMAP.

**Comment by brendannm720** [comment]
Both IMAP4 and POP3 use the same FQDN on that server.  It is IMAP4.

**Comment by firstof9** [comment]
Based on that and the errors from the log, it would indicate that there is an issue with the SSL connection or the server is dumping your connection request for some other reason. Do you have access to the IMAP server log files?

**Comment by brendannm720** [comment]
---- IMAP4S log entry made at 05/19/2020 14:10:22
Incoming IMAP (TLS) call from [redacted] at 14:09:21.
<<< * OK mail2.powerc.net modusMail IMAP4S 6.5.31.22663 ready
>>> NMDP0 CAPABILITY  
<<< * CAPABILITY IMAP4rev1 NAMESPACE LITERAL+ UIDPLUS IDLE COMPARATOR QUOTA STARTTLS AUTH=LOGIN AUTH=SCRAM-MD5 AUTH=CRAM-MD5
<<< NMDP0 OK CAPABILITY completed
>>> NMDP1 LOGIN deliveries@meteer.net ********  
<<< NMDP1 OK LOGIN completed
>>> NMDP2 LIST "" *  
<<< * LIST (\Select \Noinferiors) "/" Inbox
<<< * LIST (\Select) "/" "Sent Items"
<<< * LIST (\Select) "/" Trash
<<< NMDP2 OK LIST completed
>>> NMDP3 SELECT Inbox  
<<< * FLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)
<<< * 2 EXISTS
<<< * 0 RECENT
<<< * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)]
<<< * OK [UNSEEN 2] Message 1 is first unseen
<<< * OK [UIDNEXT 98] Predicted next UID
<<< * OK [UIDVALIDITY 481647647] UIDs are valid
<<< NMDP3 OK [READ-WRITE] opened Inbox
>>> NMDP4 SEARCH (FROM "USPSInformedDelivery@usps.gov" SUBJECT "Informed Delivery Daily Digest" SENTON "19-May-2020")  
Incoming IMAP (TLS) call from 35.138.234.118 completed at 14:10:22.

**Comment by firstof9** [comment]
Not sure why your IMAP server closed the connection unexpectedly. Maybe the timeout is set very low? I take it you run the server yourself?

**Comment by brendanm720** [comment]
It's hosted at the ISP that I work for.  The funny thing is that it's working fine for every other client on my network.

**Comment by firstof9** [comment]
Only thing I could think of is there is a timeout set very low or that you are only allowed XX amount of logins at once and the connection is getting killed due to that.

**Comment by brendanm720** [comment]
Ah.  10 simultaneous logins.

**Comment by brendanm720** [comment]
How many simultaneous logins is the code throwing at the server?  The logs don't really say anything about that.

**Comment by firstof9** [comment]
It should only be using 1, does it query for each search then disconnects.

**Comment by brendanm720** [comment]
Hmmm

**Comment by moralmunky** [comment]
Please test with another mail service to see if the results are different. If so, please to narrow down the cause from your current mail provider. If you have updated information, feel free to reopen the issue.
