### ISSUE TITLE
ISSUE: Mail and Packaging not starting due to TypeError

### ISSUE THREAD

**Issue by DeadEnded** [moralmunky/Home-Assistant-Mail-And-Packages#141]
**Describe the bug**
Mail and Packaging Integration not starting correctly.

**Environment (please complete the following information):**
 - OS: Docker
 - Type of device: NUC
 - Home Assistant version: 0.111.0
 - Docker: Core
 - Component version: 0.2.1-b4

**Logs**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 134, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 263, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 311, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 192, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 703, in get_items
    if "will arrive:" in email_msg:
TypeError: a bytes-like object is required, not 'str'
```

**Additional context**
I rolled back to HA 0.110.6 and the issue still appears to be present.  I also tried to roll M&P back to the last non-beta release - both did not resolve the issue.

Thanks,
DeadEnd

**Comment by firstof9** [comment]
Strange, do you have a Amazon email in your mailbox currently?

**Comment by DeadEnded** [comment]
Yes I do.

**Comment by firstof9** [comment]
Ok as a quick fix you can change line 703 from:
```
if "will arrive:" in email_msg:
```
to
```
if b"will arrive:" in email_msg:
```

**Comment by firstof9** [comment]
Doesn't make sense because we convert to str at  ```email_msg = email_msg.decode("utf-8")```, could you turn debugging on for the component and see what it's outputting?

**Comment by DeadEnded** [comment]
I think I see the problem - here is the last line of the debug where it errors out.
```
2020-06-11 10:24:13 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Error attempting prase Amazon email: 'utf-8' codec can't decode byte 0xd4 in position 409: invalid continuation byte
2020-06-11 10:24:13 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 134, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 263, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 311, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 192, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 703, in get_items
    if "will arrive:" in email_msg:
TypeError: a bytes-like object is required, not 'str'
```

**Comment by firstof9** [comment]
That's helpful, I'll see what I can turn up, likely have something this afternoon to fix it

**Comment by firstof9** [comment]
Well here's a work around [sensor.py](https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py) that's working how it should work when an error is encountered. Give it a shot, it should just bypass any emails that we are not expecting.

**Comment by DeadEnded** [comment]
Thanks, pulled the linked `sensor.py` and it is back to working.
Great stuff!
