### ISSUE TITLE
ISSUE: Error While Setting up mail_and_packages platform for sensor

### ISSUE THREAD

**Issue by lonelyseraphim** [moralmunky/Home-Assistant-Mail-And-Packages#143]
**Describe the bug**
Sensors fail to be created after integration installation and setup.

**Environment (please complete the following information):**
 - OS: HASSOS
 - Type of device: RPi4
 - Home Assistant version: 0.111.1
 - Hassio
 - Component version: 0.2.0

**Logs**
Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:703
Integration: Sensor (documentation, issues)
First occurred: 7:37:36 AM (1 occurrences)
Last logged: 7:37:36 AM

Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 134, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/config/custom_components/mail_and_packages/sensor.py", line 263, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 311, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 192, in update
    count[sensor] = get_items(account, "count")
  File "/config/custom_components/mail_and_packages/sensor.py", line 703, in get_items
    if "will arrive:" in email_msg:
TypeError: a bytes-like object is required, not 'str'

**Screenshots**

**Additional context**
Mail image seems to generate properly but sensors are not getting setup.

**Comment by firstof9** [comment]
Please use 0.2.1-b5 to resolve this.

Duplicate: #141

**Comment by lonelyseraphim** [comment]
I should have known you guys were on it, this fixed it right up, thank you!!
