### ISSUE TITLE
Error while setting up platform mail_and_packages

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#18]
Receiving this following, HASS 0.103.5, Python 3.7.5.

Initial thought is that this is an error when no email results form the search.

`Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 66, in async_setup_entry
    async_add_entities([MailCheck(), USPS_Mail(hass, config),
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 137, in __init__
    self.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 171, in update
    self._state = get_mails(account, self._img_out_path)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 838, in get_mails
    messageIDsString = str(data[0], encoding='utf8')
TypeError: decoding to str: need a bytes-like object, NoneType found`

When I test with an email I received  following error.

`'int' object has no attribute 'decode'`

**Comment by moralmunky** [comment]
This appears to be linked to the iCloud mail accounts. It was used since the beginning but then started throwing this error a few months ago. Changing to a gmail account resolved the error.
