### ISSUE TITLE
ISSUE: Error setting up integration

### ISSUE THREAD

**Issue by chrisceska** [moralmunky/Home-Assistant-Mail-And-Packages#194]
**Describe the bug**
 Error while setting up mail_and_packages platform for sensor

**Environment (please complete the following information):**

Tried v0.2.1-1 and v0.2.2-b13

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.0-5-amd64
python_version | 3.8.3
timezone | America/New_York
version | 0.113.2
virtualenv | false

**Logs**
```

2020-07-29 10:30:52 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2020-07-29 10:30:52 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Cleaning up image directory: /config/mail_and_packages/
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Extracting image from email
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 1
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Resizing images to 724x320...
2020-07-29 10:30:53 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting to read image /config/mail_and_packages/ATT00001.txt: cannot identify image file <_io.BufferedReader name='/config/mail_and_packages/ATT00001.txt'>
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Creating array of image files...
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Generating animated GIF
2020-07-29 10:30:53 ERROR (MainThread) [custom_components.mail_and_packages.sensor] Error attempting to generate image: Zero images were written.
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for auto-reply@usps.com with subject 1 Item Delivered results: b''
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
2020-07-29 10:30:53 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for out for delivery in emails
2020-07-29 10:30:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)


  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for


    return fut.result()


  File "/config/custom_components/mail_and_packages/sensor.py", line 137, in async_setup_entry


    sensors.append(PackagesSensor(data, variable))


  File "/config/custom_components/mail_and_packages/sensor.py", line 268, in __init__


    self.update()


  File "/config/custom_components/mail_and_packages/sensor.py", line 316, in update


    self.data.update()


  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper


    result = method(*args, **kwargs)


  File "/config/custom_components/mail_and_packages/sensor.py", line 212, in update


    total = int(get_count(account, sensor)) - data["usps_delivered"]


  File "/config/custom_components/mail_and_packages/sensor.py", line 635, in get_count


    count += find_text(data[0], account, filter_text)


  File "/config/custom_components/mail_and_packages/sensor.py", line 685, in find_text


    email_msg = email_msg.decode("utf-8")


UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2573: invalid start byte

```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by chrisceska** [comment]
I think it could be that some of the USPS Informed delivery messages have a .TXT attachment - for example:

The message it is barfing on has an file ATT00001.txt attached to it that contains the following:

Informed Delivery(TM)

Today's Deliveries: 7/29/2020

You can view your mailpieces online at the following URL:

You subscribed to this service with USPS(R) New Products & Innovation, PO Box 23972, Washington DC 200263972.

You can unsubscribe at the following URL:

Copyright(C) 2018 United States Postal Service(R). All Rights Reserved. Informed Delivery(TM) and the trade dress of USPS(R) Packaging are among the many trademarks of the U.S. Postal Service(R).

This is an automated message. Please do not reply.

**Comment by firstof9** [comment]
These emails shouldn't have attachments. Are you attempting to forward them from another email address?

**Comment by firstof9** [comment]
Try the latest beta, see if the issue persists.
