### ISSUE TITLE
Amazon Canada deliveries not being detected

### ISSUE THREAD

**Issue by jayscovill** [moralmunky/Home-Assistant-Mail-And-Packages#213]
**Describe the bug**
I received a shipment email from Amazon Canada (shipment-tracking@amazon.ca) with a delivery date for today.  The scan sensor says my email has been scanned but the integration isn't detecting the scheduled delivery or updating the sensor.mail_amazon_packages sensor.

**Environment (please complete the following information):**
 - OS: 4.12
 - Type of device: VM
 - Home Assistant version: .114.3
 - hassio
 - Component version: .21-1

I've attached an example of the email.  Let me know if you'd like any other info.

![image](https://user-images.githubusercontent.com/30603659/92398385-73953200-f0f6-11ea-953c-95c5e1f78be7.png)

**Comment by firstof9** [comment]
Your email seems to be in a different format than the normal email.
Do all your emails from Amazon.ca look similar to this?

**Comment by firstof9** [comment]
Very odd, the US emails look a bit different. I'll see what I can do.

**Comment by firstof9** [comment]
b25 should grab these now.

**Comment by jayscovill** [comment]
I've updated but now all sensors show Unavailable.

 In my log:

`2020-09-10 15:52:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 58, in async_setup_entry
    CONF_RESOURCES: entry.data[CONF_RESOURCES],
KeyError: 'resources'`

`2020-09-10 15:52:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 393, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1046, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 793, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.mail_deliveries_message. State max length is 255 characters.
2020-09-10 15:52:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 393, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1046, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 793, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.mail_deliveries_message. State max length is 255 characters.
2020-09-10 15:52:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 393, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1046, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 793, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.mail_deliveries_message. State max length is 255 characters.
2020-09-10 15:52:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 393, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1046, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 793, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.mail_deliveries_message. State max length is 255 characters.
2020-09-10 15:52:23 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 393, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1046, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 793, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.mail_deliveries_message. State max length is 255 characters.`

**Comment by firstof9** [comment]
Sounds like you're coming from a older version, hit the `Options` button on the integration and check your sensors list.

**Comment by jayscovill** [comment]
Ah OK, I've checked off all the sensors I'd like and they are showing as (0) now in the card...I still have the Fedex email's in my inbox?  Should they be showing non-zero values?  Or is there a time stamp check as well to determine if they are in the past or something like that?

**Comment by firstof9** [comment]
Yes there's a timestamp check in place.

**Comment by jayscovill** [comment]
Is the check only for date stamp and not time as well?  Because the delivery and delivered notifications are for today...They've already occurred but the date should match up if not checked for time.

**Comment by firstof9** [comment]
Correct time is not checked just the date.
