### ISSUE TITLE
ISSUE: All sensors 'Unavailable'

### ISSUE THREAD

**Issue by BoredMind** [moralmunky/Home-Assistant-Mail-And-Packages#249]
As of this morning (until this morning it was fine) all of my sensors are saying 'Unavailable' for values with details saying:

`This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.`

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi3
 - Home Assistant version: 0.118.1
 - Hassio/Docker/Core? Core
 - Component version: 0.2.2-b34

**Logs**

```
2020-11-20 14:35:19 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon order: []
2020-11-20 14:35:19 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from (['TrackingUpdates@fedex.com', 'fedexcanada@fedex.com']) with subject 1 (Delivery scheduled for today)
2020-11-20 14:35:19 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (['TrackingUpdates@fedex.com', 'fedexcanada@fedex.com']) with subject 1 (Delivery scheduled for today) results: b'' count: 0
2020-11-20 14:35:19 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from (['TrackingUpdates@fedex.com', 'fedexcanada@fedex.com']) with subject 2 (Your package is scheduled for delivery today)
2020-11-20 14:35:19 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (['TrackingUpdates@fedex.com', 'fedexcanada@fedex.com']) with subject 2 (Your package is scheduled for delivery today) results: b'' count: 0
2020-11-20 14:35:20 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/mail_and_packages/sensor.py", line 74, in async_setup_entry
sensors.append(PackagesSensor(data, variable, unique_id))
File "/config/custom_components/mail_and_packages/sensor.py", line 208, in __init__
self.update()
File "/config/custom_components/mail_and_packages/sensor.py", line 262, in update
self.data.update()
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
result = method(*args, **kwargs)
File "/config/custom_components/mail_and_packages/sensor.py", line 163, in update
total = info[ATTR_COUNT] - data[delivered]
KeyError: 'fedex_delivered'
```

**Screenshots**

![Mail](https://user-images.githubusercontent.com/67579/99856934-f8f98180-2b3e-11eb-85af-30b5c5907953.png)

I've attempted to reinstall b34 and a few other versions with no luck.  Restarted HA a few times as well.

**Comment by firstof9** [comment]
Please see #205, this happens when the config entries get out of order some how.

**Comment by firstof9** [comment]
Fixed in b35

**Comment by BoredMind** [comment]
I changed the order and that fixed it.  Thanks
