### ISSUE TITLE
ISSUE: Invalid Continuation Byte error

### ISSUE THREAD

**Issue by archerne** [moralmunky/Home-Assistant-Mail-And-Packages#293]
**Describe the bug**
Getting an invalid continuation byte error

**Environment (please complete the following information):**
 - OS: HassOS 5.6 x64
- Type of device: RPi 4 (8GB)
 - Home Assistant version: 1.0.0b4
 - Hassio/Docker/Core? Hassio
 - Component version: 0.3.0-b6

**Logs**
```
Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:683
Integration: Mail and Packages (documentation, issues)
First occurred: 9:18:26 AM (1 occurrences)
Last logged: 9:18:26 AM

Unexpected error fetching Mail and Packages (imap.gmail.com) data: 'utf-8' codec can't decode byte 0xed in position 464: invalid continuation byte
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 35, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 142, in process_emails
    info = get_count(account, sensor, True)
  File "/config/custom_components/mail_and_packages/helpers.py", line 626, in get_count
    tracking = get_tracking(data[0], account, shipper)
  File "/config/custom_components/mail_and_packages/helpers.py", line 683, in get_tracking
    email_msg = email_msg.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 464: invalid continuation byte
```

**Comment by firstof9** [comment]
Fix inbound, keep an eye out for b7.

**Comment by firstof9** [comment]
b7 should fix it up, let me know.

**Comment by archerne** [comment]
Updated. However am getting Timeout fetching Mail and Packages (imap.gmail.com) data (#278 ). Debugging it now

**Comment by archerne** [comment]
Restarted twice getting the right logging into place an it magically now works. (i know not helpful). However this issue, the UTF-8 is fixed. Will update other issue if i can recreate timeout issue
