### ISSUE TITLE
Error generating image array

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#31]
Fresh install of 105.3 in a new lxc, Ubuntu 19.10 using Mail and Packages 0.0.7 release.

Mail attachments appear in the www/mail_and_packages/ folder. Any advice?

2020-02-13 22:51:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-13 22:51:25 INFO (MainThread) [custom_components.mail_and_packages.sensor] version 0.0.6 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Informed Delivery mail
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Informed Delivery email found processing...
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Extracting image from email
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Extracting image from email
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing duplicate images.
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Removing USPS announcement images.
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Image Count: 2
2020-02-13 22:51:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Creating array of image files...
2020-02-13 22:51:25 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/munkynetadmin/.homeassistant/custom_components/mail_and_packages/sensor.py", line 66, in async_setup_entry
    async_add_entities([MailCheck(), USPS_Mail(hass, config),
  File "/home/munkynetadmin/.homeassistant/custom_components/mail_and_packages/sensor.py", line 131, in __init__
    self.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/munkynetadmin/.homeassistant/custom_components/mail_and_packages/sensor.py", line 165, in update
    self._state = get_mails(account, self._img_out_path)
  File "/home/munkynetadmin/.homeassistant/custom_components/mail_and_packages/sensor.py", line 917, in get_mails
    all_images = [io.imread(image) for image in images]
  File "/home/munkynetadmin/.homeassistant/custom_components/mail_and_packages/sensor.py", line 917, in <listcomp>
    all_images = [io.imread(image) for image in images]
  File "/srv/homeassistant/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'

**Comment by moralmunky** [comment]
FYI the 0.0.7 release still had 0.0.6 as the version number in the const file which is why the logs are showing that version number. I see it's been updated since the release. Using the files from the repository instead of the 0.0.7 release also shows the same error.

**Comment by firstof9** [comment]
Try sticking this before line 917:

``` _LOGGER.debug("Array: %s", str(images))```

Should be right before the:
```all_images = [io.imread(image) for image in images]```

**Comment by moralmunky** [comment]
This was a testing error. By forwarding the USPS email to the new account for testing, the forwarded email also exported a txt file with the email body text along with the images. I do not get a text file when processing an original email. 

Could filter them out of the array, but I think this was just special circumstances.
