### ISSUE TITLE
ISSUE: can only concatenate str

### ISSUE THREAD

**Issue by archerne** [moralmunky/Home-Assistant-Mail-And-Packages#351]
**Describe the bug**
can only concatenate str. Error from logs below. 

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPi4 8GB
 - Home Assistant version: 2021.2.0b0
 - Hassio
 - Component version: 0.3.0-b38

**Logs**
```
Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:459
Integration: Mail and Packages (documentation, issues)
First occurred: 12:26:44 PM (1 occurrences)
Last logged: 12:26:44 PM

Unexpected error fetching Mail and Packages (imap.gmail.com) data: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 64, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 104, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/config/custom_components/mail_and_packages/helpers.py", line 185, in fetch
    count[sensor] = get_mails(
  File "/config/custom_components/mail_and_packages/helpers.py", line 459, in get_mails
    filecheck = os.path.isfile(image_output_path + image_name)
TypeError: can only concatenate str (not "NoneType") to str

```
```
Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:129
Integration: Sensor (documentation, issues)
First occurred: 12:26:44 PM (1 occurrences)
Last logged: 12:26:44 PM

Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 27, in async_setup_entry
    sensors.append(ImagePathSensors(hass, entry, variable, coordinator, unique_id))
  File "/config/custom_components/mail_and_packages/sensor.py", line 129, in __init__
    self._image = self.coordinator.data[const.ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by firstof9** [comment]
Incoming PR to fix this.

**Comment by archerne** [comment]
With b39
```
Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:175
Integration: Mail and Packages (documentation, issues)
First occurred: 12:54:51 PM (1 occurrences)
Last logged: 12:54:51 PM

Unexpected error fetching Mail and Packages (imap.gmail.com) data: 'image_name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 64, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 105, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/config/custom_components/mail_and_packages/helpers.py", line 175, in fetch
    image_name = data[const.ATTR_IMAGE_NAME]
KeyError: 'image_name'
```
```
Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:129
Integration: Sensor (documentation, issues)
First occurred: 12:54:53 PM (1 occurrences)
Last logged: 12:54:53 PM

Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 27, in async_setup_entry
    sensors.append(ImagePathSensors(hass, entry, variable, coordinator, unique_id))
  File "/config/custom_components/mail_and_packages/sensor.py", line 129, in __init__
    self._image = self.coordinator.data[const.ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
```
