### ISSUE TITLE
ISSUE: Sensors failing during setup 

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages#362]
**Describe the bug**
The integration now fails to setup sensors. The mail gif does work though. I haven't changed anything that I know of.

**Environment (please complete the following information):**
 - OS: MacOS 11.2
 - Type of device: Mac mini
 - Home Assistant version: core-2021.2.1
 - Hassio/Docker/Core: Core
 - Component version: 0.2.3

**Logs**
Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 74, in async_setup_entry
    sensors.append(PackagesSensor(data, variable, unique_id))
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 216, in __init__
    self.update()
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 270, in update
    self.data.update()
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/util/__init__.py", line 285, in wrapper
    result = method(*args, **kwargs)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 133, in update
    self.fetch(account, data, sensor)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 158, in fetch
    count[sensor] = get_items(account, ATTR_COUNT, self._amazon_fwds)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 1007, in get_items
    dateobj = datetime.datetime.strptime(arrive_date, "%A, %B %d")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: ,

**Screenshots**

**Additional context**
I haven't personally changed anything that I know of. It stopped working out of the blue.

**Comment by aron7676** [comment]
I am experiencing this issue as well, on 0.3.0-b41. 
Completely clean install, I installed HASS just for this module. 

![image](https://user-images.githubusercontent.com/34799229/107442134-bfa83080-6af3-11eb-9ce2-e652e8c23760.png)

Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:124
Integration: Mail and Packages (documentation, issues)
First occurred: 4:24:10 PM (1 occurrences)
Last logged: 4:24:10 PM

Unexpected error fetching Mail and Packages (smtp.gmail.com) data: [Errno 2] No such file or directory: '/config/www/mail_and_packages/'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 64, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 98, in process_emails
    image_name = image_file_name(hass, config)
  File "/config/custom_components/mail_and_packages/helpers.py", line 124, in image_file_name
    for file in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/config/www/mail_and_packages/'


Looks like it may not be checking to see if www exists.

**Comment by moralmunky** [comment]
What is the path to your configuration directory in your installation?

**Comment by aron7676** [comment]
On mine, I am using docker, so /config. 
adding the www directory fixed my issue. Now I just have beta issues.

I added /config/www/mail_and_packages/ and reloaded. All the sensors popped up. 

Now I just need to figure out why I get 404s when pulling the image, but that is not an issue for this thread.

**Comment by firstof9** [comment]
It should auto create the directory. I'll look into it.

**Comment by julianrinaldi** [comment]
Any idea on the original error that I'm getting?

**Comment by firstof9** [comment]
> dateobj = datetime.datetime.strptime(arrive_date, "%A, %B %d")

It sounds like the email has an unexpected date format.

Should be something like "today/tomorrow,Friday Month Day" and that format isn't what's being seen.

**Comment by firstof9** [comment]
Oh sorry, this is 0.2.3. 
Try the 0.3.0 latest beta, should work fine there.

**Comment by julianrinaldi** [comment]
Installed the latest beta, deleted the integration and redid it and I'm getting the same error, as well as a new one:

Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:130
Integration: Sensor (documentation, issues)
First occurred: 3:36:45 PM (4 occurrences)
Last logged: 3:41:23 PM

```
Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 28, in async_setup_entry
    sensors.append(ImagePathSensors(hass, entry, variable, coordinator, unique_id))
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 130, in __init__
    self._image = self.coordinator.data[const.ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by firstof9** [comment]
Odd the latest beta was done to fix that error. I'll take a look.

**Comment by firstof9** [comment]
Looks like a leftover variable I didn't clean up, I'll drop a new beta that should fix that up.

**Comment by julianrinaldi** [comment]
Awesome. Thanks.

**Comment by firstof9** [comment]
Both issues should have been addressed in the latest betas. Let me know how it goes.

**Comment by julianrinaldi** [comment]
That fixed it. Thanks so much!

**Comment by julianrinaldi** [comment]
I'm getting this error again on the latest beta:

```
Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:971
Integration: Mail and Packages (documentation, issues)
First occurred: 3:58:24 PM (1 occurrences)
Last logged: 3:58:24 PM

Unexpected error fetching Mail and Packages (mail.1008n3rd.com) data: unconverted data remains: ,
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/__init__.py", line 78, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 128, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 229, in fetch
    count[sensor] = get_items(account, const.ATTR_COUNT, amazon_fwds)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 971, in get_items
    dateobj = datetime.datetime.strptime(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: ,
```
