### ISSUE TITLE
Sensors failing during setup (again)

### ISSUE THREAD

**Issue by julianrinaldi** [moralmunky/Home-Assistant-Mail-And-Packages#390]
I'm getting this error again on the latest beta:

```
Logger: custom_components.mail_and_packages
Source: custom_components/mail_and_packages/helpers.py:971
Integration: Mail and Packages (documentation, issues)
First occurred: 3:58:24 PM (1 occurrences)
Last logged: 3:58:24 PM

Unexpected error fetching Mail and Packages (mail.1008n3rd.com) data: unconverted data remains: ,
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/__init__.py", line 78, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 128, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 229, in fetch
    count[sensor] = get_items(account, const.ATTR_COUNT, amazon_fwds)
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 971, in get_items
    dateobj = datetime.datetime.strptime(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: ,
```

_Originally posted by @julianrinaldi in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/362#issuecomment-789213093_

**Comment by firstof9** [comment]
Looks like it's choking on one of your Amazon emails, can you check your mail for an amazon email and post the dates they're showing?

**Comment by julianrinaldi** [comment]
The date from the email content or from the header?

From the header: Tue, 02 Mar 2021 14:25:21 -0500

**Comment by firstof9** [comment]
Sorry the email content.

**Comment by julianrinaldi** [comment]
Here are a few different examples:

<img width="216" alt="CleanShot 2021-03-02 at 16 27 07@2x" src="https://user-images.githubusercontent.com/492435/109717566-3923c380-7b74-11eb-92e8-76c7f330738c.png">
<img width="160" alt="CleanShot 2021-03-02 at 16 26 43@2x" src="https://user-images.githubusercontent.com/492435/109717568-3923c380-7b74-11eb-88ef-4721019d0895.png">
<img width="222" alt="CleanShot 2021-03-02 at 16 26 16@2x" src="https://user-images.githubusercontent.com/492435/109717569-3923c380-7b74-11eb-97a6-b655d2443701.png">

**Comment by firstof9** [comment]
That last one is where it's choking.

Give me a few minutes and I'll have a beta available for you to test.

**Comment by julianrinaldi** [comment]
Awesome, thanks.

**Comment by firstof9** [comment]
Just to make sure there's no other that have an odd format?

Usual format is: "DayofWeek, Month #"

**Comment by julianrinaldi** [comment]
Only seeing the three formats I posted.

**Comment by firstof9** [comment]
One last request, could you check email's plain text view and see what the format for the date looks like on that 3rd one you posted?

If you're using Gmail click the 3 dots and hit "Show Original".

![image](https://user-images.githubusercontent.com/1105672/109724423-cb27ce00-7b6c-11eb-83db-49a09e11a27f.png)

**Comment by julianrinaldi** [comment]
```
Hi xxx, your package will arrive:

Tuesday, March 2, 5 p.m. – 10 p.m.
```

**Comment by firstof9** [comment]
Give 0.3.2-b1 a shot see if that clears up the error.

**Comment by julianrinaldi** [comment]
I will let you know. I actually cleared my mailbox completely because I was having issues with something else. With an empty mailbox it's working, but that doesn't mean anything. I am expecting Amazon deliveries each day for the rest of the week, so I'll be able to give you feedback soon. Thanks for your help!

**Comment by julianrinaldi** [comment]
Getting this error now:

```
Logger: homeassistant.setup
Source: custom_components/mail_and_packages/helpers.py:18
First occurred: 10:58:09 AM (1 occurrences)
Last logged: 10:58:09 AM

Setup failed for mail_and_packages: unknown error
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
    component = integration.get_component()
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 491, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/__init__.py", line 25, in <module>
    from .helpers import default_image_path, process_emails
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 18, in <module>
    import imageio as io
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/core/__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/core/util.py", line 19, in <module>
    import numpy as np
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```
Not sure if it is related to the Amazon issue or not. Also, I got an Amazon email with another format:
<img width="396" alt="CleanShot 2021-03-03 at 10 58 42@2x" src="https://user-images.githubusercontent.com/492435/109834176-edbef300-7c0f-11eb-8d49-bc4c250db66c.png">

**Comment by julianrinaldi** [comment]
Nevermind, I restarted and it started working again.

**Comment by firstof9** [comment]
Sounds like Home Assistant was still downloading a library from pip.

**Comment by julianrinaldi** [comment]
This issue seems to be fixed with beta 0.3.2-b1. However, in HACS, 0.3.2-b0 is showing as the newest version for some reason, so it keeps asking me to update. Not sure if it's just an issue with my HACS install.

![CleanShot 2021-03-04 at 15 58 08](https://user-images.githubusercontent.com/492435/110029515-8d5cae00-7d02-11eb-97a7-96d568721d2e.png)

**Comment by firstof9** [comment]
Ya, it's doing the same for me, I am not sure what's going on there. It may not like the fact I started at `b0`.

**Comment by julianrinaldi** [comment]
So while the Amazon issue seems fixed, it fails again anytime Home Assistant is restarted. Then I have to delete the integration, delete it from HACS, restart, reinstall it, restart again, and then install it again to get it to work. It gives the error I previously posted:

```
Logger: homeassistant.setup
Source: custom_components/mail_and_packages/helpers.py:18
First occurred: 10:39:21 AM (1 occurrences)
Last logged: 10:39:21 AM

Setup failed for mail_and_packages: unknown error
Traceback (most recent call last):
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 166, in _async_setup_component
    component = integration.get_component()
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 491, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/__init__.py", line 25, in <module>
    from .helpers import default_image_path, process_emails
  File "/Users/homeassistant/.homeassistant/custom_components/mail_and_packages/helpers.py", line 18, in <module>
    import imageio as io
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/core/__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/imageio/core/util.py", line 19, in <module>
    import numpy as np
  File "/Users/homeassistant/homeassistant/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

**Comment by firstof9** [comment]
I'm going to need the following info:

 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core?

**Comment by julianrinaldi** [comment]
MacOS 11
Mac Mini
Home Assistant Core 2021.3.1 in virtual environment

**Comment by firstof9** [comment]
From your vevnv, can you run `pip freeze`.

We're looking for the version of numpy it's showing as installed.

From the docker container it's `numpy==1.19.2`

**Comment by julianrinaldi** [comment]
It's showing numpy==1.19.2 as well.

**Comment by firstof9** [comment]
Apparently it's a MacOS problem:

https://github.com/numpy/numpy/issues/15947
