### ISSUE TITLE
ISSUE: M+P sensors are unavailable

### ISSUE THREAD

**Issue by riddledaxis** [moralmunky/Home-Assistant-Mail-And-Packages#415]
**Describe the bug**
Whilst running v0.3.2-b4 my sensors became unavailable. 

After a server reboot didn't fix the issue, I removed the integration from Configuration>Integration and reinstalled what was the latest beta version 0.3.2-b4. After a restart,  I readded the integration and my sensors were recreated. They, unfortunately, showed as unavailable still.

I removed the integration again and reinstalled v0.3.1 and after a restart, I configured the integration, and my sensors were again readded but still showed as unavailable.

I then repeated the procedure again and went to beta 4 but the sensors still showed as unavailable when recreated. I am now on the latest beta 0.3.2-b5 and the issue is the same.

The logs initially showed an issue with reaching my email, but I can configure the component and it sees all my mail folders, so I don't think this is an issue, then it was talking about the USPS and Amazon camera's and now the error visible in the log is about sensor.py

**Environment (please complete the following information):**
 - OS: HassOS 5.12
 - Type of device: ProxMox VM
 - Home Assistant version: core-2021.3.4, supervisor-2021-03.6
 - Component version: 0.3.2-b5

**Logs**
```
2021-03-24 20:38:11 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.2-b5 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages2021-03-25 
2021-03-24 20:38:15 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
```
```
00:05:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/config/custom_components/mail_and_packages/camera.py", line 175, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 124, in update_file_path
    image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-03-25 00:05:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/config/custom_components/mail_and_packages/camera.py", line 175, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 134, in update_file_path
    image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
```
```
2021-03-25 00:05:38 INFO (MainThread) [custom_components.mail_and_packages] Fetching Mail and Packages (outlook.office365.com) data recovered
2021-03-25 00:05:38 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 98, in device_state_attributes
    elif "_delivering" in self.type and tracking in self.data.keys():
2021-03-25 10:50:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 98, in device_state_attributes
    elif "_delivering" in self.type and tracking in self.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-25 10:55:15 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 98, in device_state_attributes
    elif "_delivering" in self.type and tracking in self.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-25 11:00:17 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 98, in device_state_attributes
    elif "_delivering" in self.type and tracking in self.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
2021-03-25 11:20:25 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 98, in device_state_attributes
    elif "_delivering" in self.type and tracking in self.data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```
**Screenshots**
![image](https://user-images.githubusercontent.com/47009467/112466305-9ff46100-8d5d-11eb-8235-00e7f74e0ced.png)

**Additional context**
The integration last worked about 4-5 days ago.

As an aside, I really like the Amazon camera for no deliveries

**Comment by firstof9** [comment]
Please [enable debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) so we can get a more accurate picture of what's going on.

**Comment by riddledaxis** [comment]
Not sure what is going on, I changed the log level to debug as requested, restarted the HA server to activate the debug logs and the sensors have started working again???

![image](https://user-images.githubusercontent.com/47009467/112516075-ce3e6480-8d8e-11eb-914e-4d8e2193b9c0.png)

I have uploaded the logs to Pastebin in case you want to look at them - https://pastebin.com/q3VQRp0A

**Comment by firstof9** [comment]
Sounds like there were issues checking your email with office365.com, which looks fixed now.

Unavailable sensors showing up is normal when there's a problem checking your email, they go back to normal once your email is accessible once again.

**Comment by riddledaxis** [comment]
Oh, ok thank you
