### ISSUE TITLE
ISSUE: ValueError: unconverted data remains: ,

### ISSUE THREAD

**Issue by jaburges** [moralmunky/Home-Assistant-Mail-And-Packages#424]
**Describe the bug**
I'm able to authenticate to outlook. However no sensors updating due to this.
I do have to use an App Password, and i have 2FA (but the app password should i believe nullify the need for 2FA)

**Environment (please complete the following information):**
 - OS: Unraid
 - Type of device: PC
 - Home Assistant version: 2021.3.4
 - Hassio/Docker/Core?  Docker core
 - Component version: 0.3.1

**Logs**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 139, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 78, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 128, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/config/custom_components/mail_and_packages/helpers.py", line 229, in fetch
    count[sensor] = get_items(account, const.ATTR_COUNT, amazon_fwds)
  File "/config/custom_components/mail_and_packages/helpers.py", line 971, in get_items
    dateobj = datetime.datetime.strptime(
  File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: ,
```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Please try the beta 0.3.2-b8 and see if that resolves your issue.
