### ISSUE TITLE
error after updating 

### ISSUE THREAD

**Issue by jes1417** [moralmunky/Home-Assistant-Mail-And-Packages#49]
So I got a little anxious last night and loaded this integration before the PR was merged to remove the image resizer, I got it working with an older release and everything was good. i NOTICED TODAY THE pr was merged so I updated via HACS and it seemed to have removed the sensors in my lovelace card.

I also noticed I was not getting any entities in the integrations page so I uninstalled, rebooted, reinstalled, rebooted and when I try to add the integration again I get an unknown error when i submit and this in the logs

```
2020-02-26 19:49:39 ERROR (MainThread) [aiohttp.server] Error handling request


Traceback (most recent call last):


  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start


    resp = await task


  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle


    resp = await handler(request)


  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware


    return await handler(request)


  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle


    result = await result


  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post


    return await super().post(request, flow_id)


  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper


    result = await method(view, request, *args, **kwargs)


  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post


    result = await self._flow_mgr.async_configure(flow_id, data)


  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure


    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)


  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step


    result: Dict = await getattr(flow, method)(user_input)


  File "/config/custom_components/mail_and_packages/config_flow.py", line 42, in async_step_user


    user_input[CONF_USERNAME], user_input[CONF_PASSWORD])


  File "/config/custom_components/mail_and_packages/config_flow.py", line 106, in _test_login


    account = imaplib.IMAP4_SSL(host, port)


  File "/usr/local/lib/python3.7/imaplib.py", line 1288, in __init__


    IMAP4.__init__(self, host, port)


  File "/usr/local/lib/python3.7/imaplib.py", line 198, in __init__


    self.open(host, port)


  File "/usr/local/lib/python3.7/imaplib.py", line 1301, in open


    IMAP4.open(self, host, port)


  File "/usr/local/lib/python3.7/imaplib.py", line 299, in open


    self.sock = self._create_socket()


  File "/usr/local/lib/python3.7/imaplib.py", line 1291, in _create_socket


    sock = IMAP4._create_socket(self)


  File "/usr/local/lib/python3.7/imaplib.py", line 289, in _create_socket


    return socket.create_connection((host, self.port))


  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection


    for res in getaddrinfo(host, port, 0, SOCK_STREAM):


  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo


    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):


socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by jes1417** [comment]
I figured it out I was using imap.google.com instead of Gmail 🤔

**Comment by firstof9** [comment]
Odd there's error handling in there to just give you a fancy error message if the server's wrong. I also have done the imap.google.com as well.
