### ISSUE TITLE
ISSUE: IMAP error parsing command

### ISSUE THREAD

**Issue by Gamerayers** [moralmunky/Home-Assistant-Mail-And-Packages#493]
**Describe the bug**
After the July 2021 release of Home Assistant, after each restart of the system, I have to remove the Mail and Packages Integration and re-add it to get it to work.

**Environment (please complete the following information):**
 - OS: Virtual Box Home Assistant
 - Type of device: Custom PC running CentOS (ClearOS 7)
 - Home Assistant version: 202107--all
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

**Logs**
```
2021-07-19 08:53:23 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
2021-07-19 08:53:25 ERROR (SyncWorker_2) [custom_components.mail_and_packages.helpers] Error searching emails: SEARCH command error: BAD [b'Could not parse command']
2021-07-19 08:53:25 ERROR (SyncWorker_2) [custom_components.mail_and_packages.helpers] Error fetching emails: FETCH command error: BAD [b'Could not parse command']
```

**Screenshots**
![image](https://user-images.githubusercontent.com/59520501/126177493-f12de65f-e72f-4bf1-a69b-e2358f565791.png)

**Additional context**
After removing the integration, and re-adding it, it works.  But then I restart again, and it fails.  Only started happening after the July 2021 updates.

**Comment by firstof9** [comment]
```log
2021-07-19 08:53:25 ERROR (SyncWorker_2) [custom_components.mail_and_packages.helpers] Error searching emails: SEARCH command error: BAD [b'Could not parse command']
2021-07-19 08:53:25 ERROR (SyncWorker_2) [custom_components.mail_and_packages.helpers] Error fetching emails: FETCH command error: BAD [b'Could not parse command']
```

Looks like something going on with your IMAP server.
Try [enabling debugging](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) to gather more information.

**Comment by Gamerayers** [comment]
Before I did anything more, I found that there was a change to the gmail that you can use app password.  That didn't fix it.

Then I uninstalled and reinstalled Mail and Packages addon, and now it is fixed.

Is there anyway in the lovelace addon to put both the USPS delivery image and the Amazon camera image?

**Comment by firstof9** [comment]
> I found that there was a change to the gmail that you can use app password.

App passwords have been around for quite some time.


> Is there anyway in the lovelace addon to put both the USPS delivery image and the Amazon camera image?

That'd be a better question for the lovelace card repo.
