### ISSUE TITLE
imamplib.IMAP4.abort:socket error: EOF

### ISSUE THREAD

**Issue by FuzzyMistborn** [moralmunky/Home-Assistant-Mail-And-Packages#50]
Seeing this in my log a few times:

```
2020-02-26 22:02:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.mail_ups_delivered fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/imaplib.py", line 1019, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/local/lib/python3.7/imaplib.py", line 1139, in _get_tagged_response
    self._get_response()
  File "/usr/local/lib/python3.7/imaplib.py", line 1047, in _get_response
    resp = self._get_line()
  File "/usr/local/lib/python3.7/imaplib.py", line 1151, in _get_line
    raise self.abort('socket error: EOF')
imaplib.IMAP4.abort: socket error: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 623, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 114, in update
    selectfolder(account, self._folder)
  File "/config/custom_components/mail_and_packages/sensor.py", line 795, in selectfolder
    rv, mailboxes = account.list()
  File "/usr/local/lib/python3.7/imaplib.py", line 585, in list
    typ, dat = self._simple_command(name, directory, pattern)
  File "/usr/local/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.7/imaplib.py", line 1021, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.IMAP4.abort: command: LIST => socket error: EOF

```

**Comment by firstof9** [comment]
Looks like a connection timeout.
About how often are you seeing this?

**Comment by FuzzyMistborn** [comment]
34 times.  Upon closer review it happened around 10pm last night and the 34 happened within about 5 minutes.  So may have been an outage or something weird.

**Comment by FuzzyMistborn** [comment]
34 times.  Upon closer review it happened around 10pm last night and the 34 happened within about 5 minutes.  So may have been an outage or something weird.

**Comment by firstof9** [comment]
I will double check my logs tonight and see if anything funky has occurred.
I'll try to add in more error catching as well.

**Comment by firstof9** [comment]
I didn't have any errors in my logs last night, but I will add more error catching and placed this on the 'todo' list :)

**Comment by FuzzyMistborn** [comment]
Haven't seen this bug since so I'm going to close.
