### ISSUE TITLE
ISSUE: Unable to use Outlook email with USPS

### ISSUE THREAD

**Issue by AngellusMortis** [moralmunky/Home-Assistant-Mail-And-Packages#515]
**Describe the bug**

Unable to use my Outlook email to get packages. 

Error message:
```
Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
```

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: RPI4
 - Home Assistant version: 2021.9.5
 - Hassio/Docker/Core? Hassio
 - Component version: 0.3.2

**Logs**

<details>

```
2021-09-11 13:48:53 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-11 13:48:53 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-11 13:49:08 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
2021-09-11 13:50:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 123, in update_file_path
image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:50:15 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:50:17 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: Camera not found
2021-09-11 13:50:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 123, in update_file_path
image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:50:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:51:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 123, in update_file_path
image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:51:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:51:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 123, in update_file_path
image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:51:43 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:52:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 123, in update_file_path
image = self._coordinator.data[ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
2021-09-11 13:52:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 641, in async_device_update
raise exc
File "/config/custom_components/mail_and_packages/camera.py", line 174, in async_update
self.update_file_path()
File "/config/custom_components/mail_and_packages/camera.py", line 133, in update_file_path
image = self._coordinator.data[ATTR_AMAZON_IMAGE]
TypeError: 'NoneType' object is not subscriptable
```

</details>

**Screenshots**

None

**Additional context**

The connection seems to actually be working since it is able to retrieve a list of my IMAP folders, but it just fails to get and process the emails.

Configuration:

* host: `outlook.office365.com`
* port: `993`
* username: my email
* password: app password
* mail folder: `Inbox/Mail`
* sensors list: Mail Updated + all USPS ones

**Comment by firstof9** [comment]
Please try with the latest beta.

**Comment by AngellusMortis** [comment]
b17 is even more broken. The integration does not even load. Same error in the logs...
```
2021-09-11 14:40:52 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
```

but now the integration just always says "retrying setup".

![image](https://user-images.githubusercontent.com/490848/132958234-d182f669-454e-4446-b7ae-7eb580659e20.png)

**Comment by firstof9** [comment]
Going to need some [debug level messages please see the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Troubleshooting#enable-debugging) on how to enable debugging messages.

**Comment by AngellusMortis** [comment]
<details>

```
2021-09-11 17:25:54 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-11 17:26:10 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.3-b17 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2021-09-11 17:26:10 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Image Name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/mail_none.gif to /config/custom_components/mail_and_packages/images/dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Image name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/no_deliveries.jpg to /config/custom_components/mail_and_packages/images/amazon/6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Amazon Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Image path: custom_components/mail_and_packages/images/
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Sensor: mail_updated Count: Sep-11-2021 05:26 PM
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SINCE "11-Sep-2021")
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'570'])
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Item Delivered) results: b'570' count: 1
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Sensor: usps_delivered Count: 1
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Expected Delivery on)
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Expected Delivery on" SINCE "11-Sep-2021")
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'163'])
2021-09-11 17:26:11 DEBUG (SyncWorker_2) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (3) emails
2021-09-11 17:26:13 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
2021-09-11 17:26:13 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 2.890 seconds (success: False)
2021-09-11 17:28:05 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.3-b17 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2021-09-11 17:28:05 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image Name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/mail_none.gif to /config/custom_components/mail_and_packages/images/dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/no_deliveries.jpg to /config/custom_components/mail_and_packages/images/amazon/6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Amazon Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image path: custom_components/mail_and_packages/images/
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: mail_updated Count: Sep-11-2021 05:28 PM
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SINCE "11-Sep-2021")
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'570'])
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Item Delivered) results: b'570' count: 1
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: usps_delivered Count: 1
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Expected Delivery on)
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Expected Delivery on" SINCE "11-Sep-2021")
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'163'])
2021-09-11 17:28:06 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (3) emails
2021-09-11 17:28:09 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
2021-09-11 17:28:09 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 4.460 seconds (success: False)
2021-09-11 17:28:22 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.3-b17 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2021-09-11 17:28:22 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image Name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/mail_none.gif to /config/custom_components/mail_and_packages/images/dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image name: dffb1018-0158-40cf-a40c-c0850eae45b2.gif
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/no_deliveries.jpg to /config/custom_components/mail_and_packages/images/amazon/6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Amazon Image Name: 6fac13c9-4ebc-4e80-b70f-952c70548eed.jpg
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Image path: custom_components/mail_and_packages/images/
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: mail_updated Count: Sep-11-2021 05:28 PM
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SINCE "11-Sep-2021")
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'570'])
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Item Delivered) results: b'570' count: 1
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Sensor: usps_delivered Count: 1
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Expected Delivery on)
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Expected Delivery on" SINCE "11-Sep-2021")
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'163'])
2021-09-11 17:28:24 DEBUG (SyncWorker_4) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (3) emails
2021-09-11 17:28:26 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
2021-09-11 17:28:26 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 3.046 seconds (success: False)
```

</details>

**Comment by AngellusMortis** [comment]
It does look like it is explicitly _only_ USPS that is having issues. Disabling USPS and everything loads. 

Amazon works. FedEx/UPS does not crash, but I do not have any deliveries from them at the moment.

**Comment by firstof9** [comment]
Interesting, and no stack trace to go with it eh?

**Comment by AngellusMortis** [comment]
No. I assuming there is a try/except that is capturing the error then then not properly logging it.

**Comment by firstof9** [comment]
Give b18 a shot when you get a chance.

**Comment by AngellusMortis** [comment]
This is with only USPS enabled. Disabled the others to cut out the noise.

<details>

```
2021-09-11 19:38:23 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.3-b18 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2021-09-11 19:38:23 DEBUG (MainThread) [custom_components.mail_and_packages] Data will be update every 0:05:00
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Image name: f7279b0a-8cbc-4455-8765-2028dc13ead1.gif
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Created: 11-Sep-2021, Today: 11-Sep-2021
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Amazon Image Name: 45f526c0-22ec-41a1-adb6-34e647334905.jpg
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Image path: custom_components/mail_and_packages/images/
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Sensor: mail_updated Count: Sep-11-2021 07:38 PM
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SINCE "11-Sep-2021")
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Item Delivered) results: b'570' count: 1
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Sensor: usps_delivered Count: 1
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Expected Delivery on)
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Expected Delivery on" SINCE "11-Sep-2021")
2021-09-11 19:38:24 DEBUG (SyncWorker_5) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (3) emails
2021-09-11 19:38:28 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (outlook.office365.com) data: Expected list, got <class 'str'>
2021-09-11 19:38:28 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 5.800 seconds (success: False)
```

</details>

**Comment by AngellusMortis** [comment]
It looks like it is _only_ the "Mail USPS Packages" and "Mail USPS Delivering" sensors that are breaking. I am guessing there is an issue parsing one of my packages?

**Comment by firstof9** [comment]
Could be but try changing.
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/78d6e1905b9414b687a7c5874bd27042b611a745/custom_components/mail_and_packages/helpers.py#L882

to
```
    _LOGGER.debug("Searching for (%s) in (%s) emails: %s", search, len(sdata), sdata)
```
so I can see if the `sdata` may be getting mangled.

**Comment by AngellusMortis** [comment]
That looks like it is the issue. `sdata` is `b'163'`

**Comment by firstof9** [comment]
One more go, I really can't think of why this would be happening since all the other functions use the same functions.
Beta 19 is up.

**Comment by AngellusMortis** [comment]
It looks everything works with b19. It could also just be because those emails dropped off from yesterday. Thanks for the help. I will circle back if it ever reappears.
