### ISSUE TITLE
ISSUE: Images for Amazon and USPS stopped working a few days ago

### ISSUE THREAD

**Issue by kylewilliams321** [moralmunky/Home-Assistant-Mail-And-Packages#573]
**Describe the bug**
The integration appears to have stopped working in my install a couple days ago. All I see now is no mail on the cards.

![image](https://user-images.githubusercontent.com/39958233/142007489-f7e03792-8020-47c4-afdc-3038609a16db.png)

**Environment (please complete the following information):**
 - OS: Raspberry pi 4
 - Type of device: 
 - Home Assistant version: core-2021.11.3
 - Hassio/Docker/Core? 
 - Component version: 0.3.3-2

**Logs**
1)
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/mail_and_packages/camera.py:155
Integration: Mail and Packages (documentation, issues)
First occurred: November 15, 2021, 3:32:28 PM (2067 occurrences)
Last logged: 8:45:53 AM

```
Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/mail_and_packages/camera.py", line 196, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 155, in update_file_path
    image = self._coordinator.data[ATTR_AMAZON_IMAGE]
KeyError: 'amazon_image'
```

2)
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/mail_and_packages/camera.py:142
Integration: Mail and Packages (documentation, issues)
First occurred: November 15, 2021, 3:32:28 PM (2067 occurrences)
Last logged: 8:45:53 AM

```
Update for camera.mail_usps_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/mail_and_packages/camera.py", line 196, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 142, in update_file_path
    image = self._coordinator.data[ATTR_IMAGE_NAME]
KeyError: 'image_name'
```

3) (this one seems to have a few different integrations in it but some of it is clearly from this mail and packages custom integration.

Logger: homeassistant.helpers.template
Source: helpers/template.py:1254
First occurred: November 15, 2021, 3:33:01 PM (60 occurrences)
Last logged: 8:43:27 AM

```
Template warning: 'int' got invalid input 'unavailable' when rendering template '{# Deliveries Sentence #} {% macro deliveries_sentence() -%} {%- if states("sensor.mail_usps_mail")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_mail")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_mail")|int <= 1 -%} pieces of mail {%- else -%} pieces of mail {%- endif -%} {{' '}}will be delivered.{{' '}} {%- if states("sensor.mail_usps_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_delivering")|int == 1 -%} USPS package is {%- else -%} USPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_fedex_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 1 -%} FedEx package is {%- else -%} Fedex packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_ups_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_ups_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_ups_delivering")|int == 1 -%} UPS package is {%- else -%} UPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_amazon_packages")|int == 0 -%} No {%- else -%} {{states("sensor.mail_amazon_packages")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_amazon_packages")|int == 1 -%} Amazon package is {%- else -%} Amazon packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- endmacro %} {{deliveries_sentence()}}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'int' got invalid input 'unknown' when rendering template '{# Deliveries Sentence #} {% macro deliveries_sentence() -%} {%- if states("sensor.mail_usps_mail")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_mail")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_mail")|int <= 1 -%} pieces of mail {%- else -%} pieces of mail {%- endif -%} {{' '}}will be delivered.{{' '}} {%- if states("sensor.mail_usps_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_usps_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_usps_delivering")|int == 1 -%} USPS package is {%- else -%} USPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_fedex_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_fedex_delivering")|int == 1 -%} FedEx package is {%- else -%} Fedex packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_ups_delivering")|int == 0 -%} No {%- else -%} {{states("sensor.mail_ups_delivering")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_ups_delivering")|int == 1 -%} UPS package is {%- else -%} UPS packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- if states("sensor.mail_amazon_packages")|int == 0 -%} No {%- else -%} {{states("sensor.mail_amazon_packages")|int}} {%- endif -%} {{' '}} {%- if states("sensor.mail_amazon_packages")|int == 1 -%} Amazon package is {%- else -%} Amazon packages are {%- endif -%} {{' '}}in transit.{{' '}} {%- endmacro %} {{deliveries_sentence()}}' but no default was specified. Currently 'int' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'float' got invalid input 'None' when rendering template '### Current Metrics: <font color="firebrick"><ha-icon icon="mdi:heart-pulse"></ha-icon></font> **Heart Rate (bpm):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Heart Rate Bpm") }} <font color="darkorange"><ha-icon icon="mdi:omega"></ha-icon></font> **Resistance (%):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Resistance %") }} <font color="darkorchid"><ha-icon icon="mdi:speedometer"></ha-icon></font> **Speed (Mph):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Mph") }} <font color="darkorchid"><ha-icon icon="mdi:speedometer"></ha-icon></font> **Speed (Kph):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Kph") }} <font color="mediumseagreen"><ha-icon icon="mdi:sine-wave"></ha-icon></font> **Cadence Rpm:** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Cadence Rpm") }} <font color="orangered"><ha-icon icon="mdi:lightning-bolt"></ha-icon></font> **Power (W):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Power W") }} --- ### Latest Workout Summary: <ha-icon icon="mdi:calendar-range"></ha-icon> - **Date:** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Start Time")|float|timestamp_custom('%Y/%m/%d &raquo; %H:%M') }} - {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "End Time")|float|timestamp_custom('%H:%M') }} ({{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Duration Min") }} mins) {% if (state_attr('sensor.peloton_Sir_Farts_A_Lot', 'Workout Image')|string != 'None') %} <img src="{{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Workout Image") }}"> {% endif %} **{{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Ride Title") }} ({{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Workout Type") }})** - *{{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Description") }}* - Instructor: {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Instructor") }} --- ### Latest Workout Metrics: <font color="royalblue"><ha-icon icon="mdi:map-marker-distance"></ha-icon></font> - **Distance (Mi):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Distance Mi") | float | round(2) }} <font color="firebrick"><ha-icon icon="mdi:heart-pulse"></ha-icon></font> - **Heart Rate (bpm):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Heart Rate Average Bpm") | float | round(0) }} avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Heart Rate Max Bpm") | float | round(0) }} max <font color="darkorange"><ha-icon icon="mdi:omega"></ha-icon></font> - **Resistance:** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Resistance Average %") | float | round(0) }}% avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Resistance Max %") | float | round(0) }}% max <font color="darkorchid"><ha-icon icon="mdi:speedometer"></ha-icon></font> - **Speed (Mph):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Average Mph") | float | round(2) }} avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Max Mph") | float | round(2) }} max <font color="darkorchid"><ha-icon icon="mdi:speedometer"></ha-icon></font> - **Speed (Kph):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Average Kph") | float | round(2) }} avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Speed Max Kph") | float | round(2) }} max <font color="mediumseagreen"><ha-icon icon="mdi:sine-wave"></ha-icon></font> - **Cadence (Rpm):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Cadence Average Rpm") | float | round(0) }} avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Cadence Max Rpm") | float | round(0) }} max <font color="orangered"><ha-icon icon="mdi:lightning-bolt"></ha-icon></font> - **Power (W):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Power Average W") | float | round(2) }} avg / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Power Max W") | float | round(2) }} max <font color="orangered"><ha-icon icon="mdi:lightning-bolt"></ha-icon></font> - **Total Work:** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Total Work") | float | round(0) }} J <font color="orangered"><ha-icon icon="mdi:lightning-bolt"></ha-icon></font> - **Output (KJ):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Output Kj") | float | round(2) }} <font color="crimson"><ha-icon icon="mdi:food"></ha-icon></font> - **Calories (KCal):** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Calories KCal") }} <font color="yellowgreen"><ha-icon icon="mdi:chevron-triple-up"></ha-icon></font> - **Leaderboard Rank:** {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Leaderboard Rank") }} / {{ state_attr('sensor.peloton_Sir_Farts_A_Lot', "Leaderboard Users") }} ({{ 100 - (100 * (state_attr('sensor.peloton_Sir_Farts_A_Lot', "Leaderboard Rank") | int ) / (state_attr('sensor.peloton_Sir_Farts_A_Lot', "Leaderboard Users") | int)) | round(0) }}%)' but no default was specified. Currently 'float' will return '0', however this template will fail to render in Home Assistant core 2022.1
```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

Here is the snippet from config.yaml

```
sensor:
  - platform: template
    sensors:
      mail_deliveries_message:
        friendly_name: "Deliveries Summary"
        value_template: >
          {# Deliveries Sentence #}
            {% macro deliveries_sentence() -%}
                  {%- if states("sensor.mail_usps_mail")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_usps_mail")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_usps_mail")|int <= 1 -%}
                    pieces of mail
                  {%- else -%}
                    pieces of mail
                  {%- endif -%}
                {{' '}}will be delivered.{{' '}} 
                  {%- if states("sensor.mail_usps_delivering")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_usps_delivering")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_usps_delivering")|int == 1 -%}
                    USPS package is
                  {%- else -%}
                    USPS packages are
                  {%- endif -%}
                {{' '}}in transit.{{' '}}
                  {%- if states("sensor.mail_fedex_delivering")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_fedex_delivering")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_fedex_delivering")|int == 1 -%}
                    FedEx package is
                  {%- else -%}
                    Fedex packages are
                  {%- endif -%}
                {{' '}}in transit.{{' '}}
                {%- if states("sensor.mail_ups_delivering")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_ups_delivering")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_ups_delivering")|int == 1 -%}
                    UPS package is
                  {%- else -%}
                    UPS packages are
                  {%- endif -%}
                {{' '}}in transit.{{' '}}
                {%- if states("sensor.mail_amazon_packages")|int == 0 -%}
                    No
                  {%- else -%}
                    {{states("sensor.mail_amazon_packages")|int}}
                  {%- endif -%}
                {{' '}} 
                  {%- if states("sensor.mail_amazon_packages")|int == 1 -%}
                    Amazon package is
                  {%- else -%}
                    Amazon packages are
                  {%- endif -%}
                {{' '}}in transit.{{' '}}
            {%- endmacro %}
          {{deliveries_sentence()}}
```

**Comment by firstof9** [comment]
Your template issue has [already been addressed](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions/563). I've now pinned that topic in the discussions tab.

The camera errors are showing up as your sensors are not updating. Look for another error message from `mail_and_packages`.

**Comment by firstof9** [comment]
The latest beta has a fix that should prevent the errors for occurring when your sensor data is missing.

**Comment by kylewilliams321** [comment]
It must be this then:
This error originated from a custom integration.

Logger: custom_components.mail_and_packages.helpers
Source: custom_components/mail_and_packages/helpers.py:379
Integration: Mail and Packages (documentation, issues)
First occurred: 10:05:01 AM (1 occurrences)
Last logged: 10:05:01 AM

Error logging into IMAP Server: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'

Looks like I have to reauthenticate my google email in order for the sensor to read through my messages. I'll look into that but if you know and can point me in the right direction that would be great.
Thanks.

**Comment by firstof9** [comment]
Make sure you're using the [app password feature for gmail, covered in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki/Configuration-and-Email-Settings#gmail).
