### ISSUE TITLE
Yahoo mail with valid app password not working

### ISSUE THREAD

**Issue by tkdrob** [moralmunky/Home-Assistant-Mail-And-Packages#629]
**Describe the bug**
I am using yahoo mail with a valid app password. Gmail seems to work fine.
Let me know if you need more info

**Environment (please complete the following information):**
 - OS: Debian
 - Type of device: NUC
 - Home Assistant version: 22.2.6
 - Hassio/Docker/Core? Docker
 - Component version: 0.3.4-b19

**Logs**
Paste your error logs here.

```
2022-02-13 10:59:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/imaplib.py", line 1047, in _command_complete
    typ, data = self._get_tagged_response(tag, expect_bye=logout)
  File "/usr/lib/python3.9/imaplib.py", line 1165, in _get_tagged_response
    self._check_bye()
  File "/usr/lib/python3.9/imaplib.py", line 961, in _check_bye
    raise self.abort(bye[-1].decode(self._encoding, 'replace'))
imaplib.IMAP4.abort: IMAP4rev1 Server logging out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/tkdro/core/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/mnt/c/Users/tkdro/core/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/mnt/c/Users/tkdro/core/venv/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/mnt/c/Users/tkdro/core/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/mnt/c/Users/tkdro/core/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/mnt/c/Users/tkdro/core/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/mnt/c/Users/tkdro/core/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/mnt/c/Users/tkdro/core/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/mnt/c/Users/tkdro/core/config/custom_components/mail_and_packages/config_flow.py", line 259, in async_step_user
    return await self.async_step_config_2()
  File "/mnt/c/Users/tkdro/core/config/custom_components/mail_and_packages/config_flow.py", line 292, in async_step_config_2
    return await self._show_config_2(user_input)
  File "/mnt/c/Users/tkdro/core/config/custom_components/mail_and_packages/config_flow.py", line 313, in _show_config_2
    data_schema=_get_schema_step_2(self._data, user_input, defaults),
  File "/mnt/c/Users/tkdro/core/config/custom_components/mail_and_packages/config_flow.py", line 178, in _get_schema_step_2
    _get_mailboxes(
  File "/mnt/c/Users/tkdro/core/config/custom_components/mail_and_packages/config_flow.py", line 126, in _get_mailboxes
    status, folderlist = account.list()
  File "/usr/lib/python3.9/imaplib.py", line 599, in list
    typ, dat = self._simple_command(name, directory, pattern)
  File "/usr/lib/python3.9/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.9/imaplib.py", line 1049, in _command_complete
    raise self.abort('command: %s => %s' % (name, val))
imaplib.IMAP4.abort: command: LIST => IMAP4rev1 Server logging out
```

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by tkdrob** [comment]
Update: this seems to work sometimes, but not always. I'll update this when I can get the full debug log.

**Comment by tkdrob** [comment]
Working on more info

**Comment by rjbrown99** [comment]
I'm seeing the same thing - also using Yahoo Mail as my integration point and this stopped working. Here are the error messages generated.

https://ibb.co/1JN8RQm
https://ibb.co/8r320Nw
https://ibb.co/DMMnMqq
https://ibb.co/jVtkTPm
