### ISSUE TITLE
ISSUE: Amazon sensor missing data

### ISSUE THREAD

**Issue by broyuken** [moralmunky/Home-Assistant-Mail-And-Packages#780]
**Describe the bug**

I updated to 2023.1 this morning and Mail and Packages stopped working. It just seems to be Amazon and usps that broke. 

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: [e.g. 0.105.5]
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]

0.3.5-b21
2023.1 
HassOS
**Logs**
Paste your error logs here.

Logger: homeassistant.components.sensor
Source: custom_components/mail_and_packages/sensor.py:129 
Integration: Sensor (documentation, issues) 
First occurred: 7:07:51 AM (2 occurrences) 
Last logged: 7:07:51 AM

Error adding entities for domain sensor with platform mail_and_packages
Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/mail_and_packages/sensor.py", line 129, in extra_state_attributes
    attr[ATTR_ORDER] = data[AMAZON_ORDER]
KeyError: 'amazon_order'

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by broyuken** [comment]
After some time these sensors came back, but the logs still show on reboot
