### ISSUE TITLE
ISSUE: can’t update 

### ISSUE THREAD

**Issue by broyuken** [moralmunky/Home-Assistant-Mail-And-Packages#835]
**Describe the bug**
Hacs tells me there is an update but I can’t update. 

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS] HassOS
 - Type of device: [e.g. RPi3/NUC/Synology] NUC
 - Home Assistant version: [e.g. 0.105.5] 2023.6.1
 - Hassio/Docker/Core? 
 - Component version: [e.g. 0.1.2]0.3.15

**Logs**
Paste your error logs here.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/base.py:995 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 6:39:11 AM (1 occurrences) 
Last logged: 6:39:11 AM

[140066352443472] Could not download, see log for details
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/config/custom_components/hacs/update.py", line 85, in async_install
    await self.repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by PDXUser** [comment]
I can confirm this is the same thing happening on my end.  This is my first hint of an error, then after that, the same error text as the OP's error.  It seems that it can't find the release tag:

```
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:899
Integration: HACS (documentation, issues)
First occurred: 4:47:04 AM (1 occurrences)
Last logged: 4:47:04 AM

<Integration moralmunky/Home-Assistant-Mail-And-Packages> No assets found for release 'tags/0.3.16'
```

**Comment by droans** [comment]
Seems the release file wasn't attached to the release.

You can still update to 0.3.15. Go to Hacs=>Integrations. Select Mail and Packages. Click the overflow menu button and select "Redownload". Choose 0.3.15 from the options and click "Download".

**Comment by PDXUser** [comment]
Thanks! Updated successfully by following @droans instructions!
