### ISSUE TITLE
ISSUE: Integration Fails to Update Image

### ISSUE THREAD

**Issue by djripcord** [moralmunky/Home-Assistant-Mail-And-Packages#851]
**Describe the bug**
Integration does not work at all. The package count never changes, and package camera entity never is updated. It constantly remains "no mail".

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Lenovo ThinkCentre
 - Home Assistant version: 2023.8.4
 - Super 2023.8.1
 - Component version: 0.3.18

**Logs**
Logger: homeassistant.helpers.entity
Source: custom_components/mail_and_packages/camera.py:146
Integration: Mail and Packages (documentation, issues)
First occurred: September 29, 2023 at 4:05:29 AM (240 occurrences)
Last logged: October 2, 2023 at 7:11:07 AM

Update for camera.mail_usps_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/mail_and_packages/camera.py", line 210, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 146, in update_file_path
    image = self._coordinator.data[ATTR_IMAGE_NAME]
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'image_name'



**Additional context**
I am not sure how to parse out this error. There seems to be an issue with the image name attribute, and this remains true as the exact same error for both amazon and USPS.

**Comment by firstof9** [comment]
Enable debug logging and post or attache the log.

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/1105672/798cc682-d73d-45df-8bda-b7ef42005a63)

**Comment by djripcord** [comment]
> Enable debug logging and post or attache the log.
> 
> ![image](https://user-images.githubusercontent.com/1105672/272280576-798cc682-d73d-45df-8bda-b7ef42005a63.png)

Sorry to be ignorant. I have had debug enabled for weeks, but I am unsure where to find the log. The one I posted is an excerpt from the primary system logs.
Where would I find the logs for this integration?

**Comment by firstof9** [comment]
`home-assistant.log` in your `/config` directory

**Comment by djripcord** [comment]
Here are a few log excerpts:
`2023-09-29 04:04:59.601 ERROR (SyncWorker_8) [custom_components.mail_and_packages.helpers] Network error while connecting to server: [Errno -3] Try again
2023-09-29 04:04:59.608 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (mail.[REDACTED].com) data in 5.144 seconds (success: True)
2023-09-29 04:04:59.618 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Updating system image path to: custom_components/mail_and_packages/images/
2023-09-29 04:04:59.619 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] External URL not set in configuration.`

`2023-09-29 04:05:29.620 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2023-09-29 04:05:29.620 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2023-09-29 04:05:29.620 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 699, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/mail_and_packages/camera.py", line 210, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 146, in update_file_path
    image = self._coordinator.data[ATTR_IMAGE_NAME]
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
 KeyError: 'amazon_image'
2023-09-29 04:08:59.626 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2023-09-29 04:08:59.626 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2023-09-29 04:08:59.626 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails`

That's about all I got. The same set of errors appears repeatedly through the logs.

**Comment by firstof9** [comment]
Based on these logs it doesn't look like you've enabled the `Mail USPS Mail` sensor in the configuration, that would be why you get the "No Mail" image all the time.

**Comment by djripcord** [comment]
> Based on these logs it doesn't look like you've enabled the `Mail USPS Mail` sensor in the configuration, that would be why you get the "No Mail" image all the time.

This resolved my issue. I feel silly. Thanks.

**Comment by firstof9** [comment]
Anytime!
