### ISSUE TITLE
ISSUE: Error setting up entry imap.mail.yahoo.com for mail_and_packages

### ISSUE THREAD

**Issue by coharness** [moralmunky/Home-Assistant-Mail-And-Packages#864]
**Describe the bug**
After updating Home Assistant version, Mail and Packages fails to start.

**Environment (please complete the following information):**
 - OS: Docker install
 - Type of device: Synology
 - Home Assistant version: 2023.11.2
 - Component version: 0.3.19

**Logs**
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 8:43:44 AM (1 occurrences)
Last logged: 8:43:44 AM

Error setting up entry imap.mail.yahoo.com for mail_and_packages
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mail_and_packages/__init__.py", line 99, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mail_and_packages/__init__.py", line 247, in _async_update_data
    data = await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: aiohttp connection lost

**Comment by firstof9** [comment]
Looks like home assistant blew up. Try restarting HA.

**Comment by coharness** [comment]
I've restarted twice today and still have this issue. I'm also having a lot of problems with several other integrations, so it might not be that there's a problem with this one specifically. I'll update when I know more.
