### ISSUE TITLE
ISSUE: Error on setup after updating to 0.1.3

### ISSUE THREAD

**Issue by elardner** [moralmunky/Home-Assistant-Mail-And-Packages#88]
I've been having trouble with the integration since the update to 0.1.3. I got it re-setup with the 2 step process and it seemed to work until a reboot. After reboot the integration seemed to break. I was getting "unknown" for all existing entities. I uninstalled and reinstalled, and re-setup, which seemed to fix until the next reboot when things went away again.

On the third try messing with things, I have uninstalled, reinstalled and am now getting the following error on boot:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/mail_and_packages/sensor.py", line 69, in async_setup_entry
    async_add_entities([MailCheck(data), USPS_Mail(hass, data),
  File "/config/custom_components/mail_and_packages/sensor.py", line 188, in __init__
    self.update()
  File "/config/custom_components/mail_and_packages/sensor.py", line 228, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/mail_and_packages/sensor.py", line 131, in update
    self._gif_duration, self._image_name)
  File "/config/custom_components/mail_and_packages/sensor.py", line 1070, in get_mails
    cleanup_images(image_output_path)
  File "/config/custom_components/mail_and_packages/sensor.py", line 1196, in cleanup_images
    os.remove(path + file)
FileNotFoundError: [Errno 2] No such file or directory: '/config/images/mail_and_packagesmail_today.gif'`

Not sure where to go from here.

 - OS: Hass.io
 - Type of device: RPi 3B+
 - Home Assistant version: 0.108.3
 - Component version: 0.1.3

**Comment by firstof9** [comment]
For now please change your image path to ```/config/images/mail_and_packages/```

**Comment by moralmunky** [comment]
@elardner FYI, it was because the trailing / was missing from your configuration image path.

Your configuration: /config/images/mail_and_packages
@firstof9 suggestion: /config/images/mail_and_packages/

You can see in the last line of your log, `[Errno 2] No such file or directory: '/config/images/mail_and_packagesmail_today.gif'`, it's looking for a folder named mail_and_packagesmail_today.gif because the slash is missing.

@firstof9 has now added code to check if the user has provided the trailing slash or not.
