### ISSUE TITLE
Getting error in the logfile

### ISSUE THREAD

**Issue by sambeetm** [moralmunky/Home-Assistant-Mail-And-Packages#907]
Getting the following error in the log file. How to resolve it ?

**Environment (please complete the following information):**
 - OS: [e.g. HassOS/Raspbian/CentOS]   HassOS
 - Type of device: [e.g. RPi3/NUC/Synology]   NUC
 - Home Assistant version: [e.g. 0.105.5]        Core 2024.6.1, Supervisor 2024.06.0 
 - Hassio/Docker/Core?     Docker
 - Component version: [e.g. 0.1.2]   0.3.27

```
2024-06-08 18:46:01.219 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_usps_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/mail_and_packages/camera.py", line 210, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 148, in update_file_path
    image = self._coordinator.data[ATTR_IMAGE_NAME]
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'image_name'
2024-06-08 18:46:01.224 ERROR (MainThread) [homeassistant.helpers.entity] Update for camera.mail_amazon_delivery_camera fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/mail_and_packages/camera.py", line 210, in async_update
    self.update_file_path()
  File "/config/custom_components/mail_and_packages/camera.py", line 160, in update_file_path
    image = self._coordinator.data[ATTR_AMAZON_IMAGE]
            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
```

**Comment by firstof9** [comment]
Should be fixed in the next release.
