### ISSUE TITLE
ISSUE: Blocking call event loop during package initialization causes HA to hang

### ISSUE THREAD

**Issue by chriswood1001** [moralmunky/Home-Assistant-Mail-And-Packages#929]
**Describe the bug**
Mail-and-packages freezes during initialization (after I successfully link my gMail account and select my folder + sensors). Home Assistant reports an event loop, freezes, and must be restarted. Home Assistant no longer boots with the last log entry on boot attempts being "2024-06-25 23:12:57.286 ERROR (MainThread) [custom_components.mail_and_packages.helpers] Error searching emails: command: SEARCH => unexpected response: b'7csp12957rwo;'" Removing the mail-and-packages from the custom_components directory allowed me to boot, disable and then remove the integration. 100% reproducable.

**Environment (please complete the following information):**
 - OS: Docker
 - Type of device: Dedicated server hardware, Xeon E-2386G x6 core, 64 GB DDR4
 - Home Assistant version: 2024.06.4
 - Docker
 - Component version: v0.3.29

**Logs**
```
2024-06-25 23:07:19.056 ERROR (MainThread) [custom_components.mail_and_packages] Problem updating sensors: 'count'
2024-06-25 23:07:19.056 ERROR (MainThread) [custom_components.mail_and_packages] Error fetching Mail and Packages (imap.gmail.com) data: 'count'
2024-06-25 23:07:19.056 ERROR (MainThread) [custom_components.mail_and_packages] Error updating sensor data: 'count'
2024-06-25 23:07:19.603 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 1171: with open(filepath, "wb") as the_file: (offender: /config/custom_components/mail_and_packages/helpers.py, line 1171: with open(filepath, "wb") as the_file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/mail_and_packages/helpers.py", line 1171, in download_img
    with open(filepath, "wb") as the_file:
2024-06-25 23:07:25.271 ERROR (SyncWorker_26) [custom_components.mail_and_packages.helpers] Error fetching emails: command: FETCH => unexpected response: b'7csp12957rwo;'
```

**Additional context**
I had this working originally for over a year, upgraded mail-and-packages through HACS and had an issue (I forget what the issue was). As part of troubleshooting I uninstalled the package, restarted HA, re-installed this package and now am facing this issue preventing HA from booting. 100% reproducible. 

I've linked it to gMail, see my directories, select "Home/Mail" (which is where I filter all my package emails). I've selected all sensors for Amazon, DHL, FedEx, plus the last two sensors regarding summaries.

**Comment by firstof9** [comment]
Seems like your download is either wrong or something's been cached, as there is no code in `download_img` that matches what the traceback is producing.

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/6d5c0fdeeae215784495c14c6e9ad33030e8df1c/custom_components/mail_and_packages/helpers.py#L1169-L1188

**Comment by droans** [comment]
It's definitely from this package. I'm experiencing the same issue. The only way I could get HA to load was to remove `mail_and_packages` from my custom components directory.

**Comment by droans** [comment]
[Here's the actual line in 0.3.28.](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/475c9e2fa233101e51dc11478d94b9d6be2fc867/custom_components/mail_and_packages/helpers.py#L1171.

This is the same version I am running. It looks like it was changed in 0.3.29 to use `hass.async_add_executor_job`.

**Comment by firstof9** [comment]
Correct meaning your integration didn't update or something.

**Comment by chriswood1001** [comment]
Glad I wasn't the only one facing the issue. To solve this I not only uninstalled the component, but also manually removed the mail_and_packages directory from the /config/custom_components/ folder. This should occur when uninstalling through HACS but for whatever reason did not. HA restart, then re-install mail_and_packages through HACS once again. Now I'm able to link without issue.

**Comment by firstof9** [comment]
Gonna chalk this one up to HACS issues.
