### ISSUE TITLE
Updated to .4.0b1 and it no longer loads

### ISSUE THREAD

**Issue by bschatzow** [moralmunky/Home-Assistant-Mail-And-Packages#949]
Went back to b0 and it goes back to working
Logger: homeassistant.setup
Source: setup.py:322
First occurred: 5:25:01 AM (1 occurrences)
Last logged: 5:25:01 AM

Setup failed for custom integration 'mail_and_packages': Unable to import component: cannot import name 'CONFIG_VERSION' from 'custom_components.mail_and_packages.const' (/config/custom_components/mail_and_packages/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mail_and_packages/__init__.py", line 13, in <module>
    from .const import (
ImportError: cannot import name 'CONFIG_VERSION' from 'custom_components.mail_and_packages.const' (/config/custom_components/mail_and_packages/const.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/mail_and_packages/__init__.py", line 13, in <module>
    from .const import (
ImportError: cannot import name 'CONFIG_VERSION' from 'custom_components.mail_and_packages.const' (/config/custom_components/mail_and_packages/const.py)

**Comment by DeltaNu1142** [comment]
I have the same issue, following.

**Comment by firstof9** [comment]
Looks like a bad HACS download.

**Comment by bschatzow** [comment]
I'll try again. I did try it twice last night

**Comment by bschatzow** [comment]
Just tried again.  Same error. Maybe bad code at GitHub?

**Comment by iganeshk** [comment]
> Looks like a bad HACS download.

I suspect this commit

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/commit/69aba51a5ce683e667b8f2b4e1413af667dccf3e#diff-c2dfae03dbf1569e044efacc518bd596794430c698d2481842dbb720e5cabd71

![image](https://github.com/user-attachments/assets/fd356c76-be78-40d3-adc8-6bfab169ed2d)

**Comment by firstof9** [comment]
Looks like a github action might be removing it from `const.py` let me see what I can do.

**Comment by firstof9** [comment]
`0.4.0b2` should be showing up shortly with a fix for this.

**Comment by bschatzow** [comment]
O. 4.0b2 loads (no errors in log) all sensors show unavailable. Going back to b0
